// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["amazon-bedrock"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "amazon-bedrock",
    artifactBasename: "api.js",
  });
}
export const discoverBedrockModels: FacadeModule["discoverBedrockModels"] = ((...args) =>
  loadFacadeModule()["discoverBedrockModels"](...args)) as FacadeModule["discoverBedrockModels"];
export const mergeImplicitBedrockProvider: FacadeModule["mergeImplicitBedrockProvider"] = ((
  ...args
) =>
  loadFacadeModule()["mergeImplicitBedrockProvider"](
    ...args,
  )) as FacadeModule["mergeImplicitBedrockProvider"];
export const resetBedrockDiscoveryCacheForTest: FacadeModule["resetBedrockDiscoveryCacheForTest"] =
  ((...args) =>
    loadFacadeModule()["resetBedrockDiscoveryCacheForTest"](
      ...args,
    )) as FacadeModule["resetBedrockDiscoveryCacheForTest"];
export const resolveBedrockConfigApiKey: FacadeModule["resolveBedrockConfigApiKey"] = ((...args) =>
  loadFacadeModule()["resolveBedrockConfigApiKey"](
    ...args,
  )) as FacadeModule["resolveBedrockConfigApiKey"];
export const resolveImplicitBedrockProvider: FacadeModule["resolveImplicitBedrockProvider"] = ((
  ...args
) =>
  loadFacadeModule()["resolveImplicitBedrockProvider"](
    ...args,
  )) as FacadeModule["resolveImplicitBedrockProvider"];
