// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  discoverBedrockModels,
  mergeImplicitBedrockProvider,
  resetBedrockDiscoveryCacheForTest,
  resolveBedrockConfigApiKey,
  resolveImplicitBedrockProvider,
} from "../../extensions/amazon-bedrock/api.js";
