// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  isAllowedBlueBubblesSender,
  resolveBlueBubblesGroupRequireMention,
  resolveBlueBubblesGroupToolPolicy,
} from "../../extensions/bluebubbles/api.js";
