// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  browserHandlers,
  createBrowserPluginService,
  createBrowserTool,
  handleBrowserGatewayRequest,
  registerBrowserCli,
} from "../../extensions/browser/runtime-api.js";
