// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["browser"];
type FacadeModule = FacadeEntry["module"];
import {
  createLazyFacadeObjectValue,
  loadBundledPluginPublicSurfaceModuleSync,
} from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "browser",
    artifactBasename: "runtime-api.js",
  });
}
export const browserHandlers: FacadeModule["browserHandlers"] = createLazyFacadeObjectValue(
  () => loadFacadeModule()["browserHandlers"] as object,
) as FacadeModule["browserHandlers"];
export const createBrowserPluginService: FacadeModule["createBrowserPluginService"] = ((...args) =>
  loadFacadeModule()["createBrowserPluginService"](
    ...args,
  )) as FacadeModule["createBrowserPluginService"];
export const createBrowserTool: FacadeModule["createBrowserTool"] = ((...args) =>
  loadFacadeModule()["createBrowserTool"](...args)) as FacadeModule["createBrowserTool"];
export const handleBrowserGatewayRequest: FacadeModule["handleBrowserGatewayRequest"] = ((
  ...args
) =>
  loadFacadeModule()["handleBrowserGatewayRequest"](
    ...args,
  )) as FacadeModule["handleBrowserGatewayRequest"];
export const registerBrowserCli: FacadeModule["registerBrowserCli"] = ((...args) =>
  loadFacadeModule()["registerBrowserCli"](...args)) as FacadeModule["registerBrowserCli"];
