// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["byteplus"];
type FacadeModule = FacadeEntry["module"];
import {
  createLazyFacadeArrayValue,
  loadBundledPluginPublicSurfaceModuleSync,
} from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "byteplus",
    artifactBasename: "api.js",
  });
}
export const buildBytePlusCodingProvider: FacadeModule["buildBytePlusCodingProvider"] = ((
  ...args
) =>
  loadFacadeModule()["buildBytePlusCodingProvider"](
    ...args,
  )) as FacadeModule["buildBytePlusCodingProvider"];
export const buildBytePlusModelDefinition: FacadeModule["buildBytePlusModelDefinition"] = ((
  ...args
) =>
  loadFacadeModule()["buildBytePlusModelDefinition"](
    ...args,
  )) as FacadeModule["buildBytePlusModelDefinition"];
export const buildBytePlusProvider: FacadeModule["buildBytePlusProvider"] = ((...args) =>
  loadFacadeModule()["buildBytePlusProvider"](...args)) as FacadeModule["buildBytePlusProvider"];
export const BYTEPLUS_BASE_URL: FacadeModule["BYTEPLUS_BASE_URL"] =
  loadFacadeModule()["BYTEPLUS_BASE_URL"];
export const BYTEPLUS_CODING_BASE_URL: FacadeModule["BYTEPLUS_CODING_BASE_URL"] =
  loadFacadeModule()["BYTEPLUS_CODING_BASE_URL"];
export const BYTEPLUS_CODING_MODEL_CATALOG: FacadeModule["BYTEPLUS_CODING_MODEL_CATALOG"] =
  createLazyFacadeArrayValue(
    () => loadFacadeModule()["BYTEPLUS_CODING_MODEL_CATALOG"] as unknown as readonly unknown[],
  ) as FacadeModule["BYTEPLUS_CODING_MODEL_CATALOG"];
export const BYTEPLUS_MODEL_CATALOG: FacadeModule["BYTEPLUS_MODEL_CATALOG"] =
  createLazyFacadeArrayValue(
    () => loadFacadeModule()["BYTEPLUS_MODEL_CATALOG"] as unknown as readonly unknown[],
  ) as FacadeModule["BYTEPLUS_MODEL_CATALOG"];
