// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  applyChutesApiKeyConfig,
  applyChutesConfig,
  applyChutesProviderConfig,
  buildChutesModelDefinition,
  buildChutesProvider,
  CHUTES_BASE_URL,
  CHUTES_DEFAULT_MODEL_ID,
  CHUTES_DEFAULT_MODEL_REF,
  CHUTES_MODEL_CATALOG,
  discoverChutesModels,
} from "../../extensions/chutes/api.js";
