// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["chutes"];
type FacadeModule = FacadeEntry["module"];
import {
  createLazyFacadeArrayValue,
  loadBundledPluginPublicSurfaceModuleSync,
} from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "chutes",
    artifactBasename: "api.js",
  });
}
export const applyChutesApiKeyConfig: FacadeModule["applyChutesApiKeyConfig"] = ((...args) =>
  loadFacadeModule()["applyChutesApiKeyConfig"](
    ...args,
  )) as FacadeModule["applyChutesApiKeyConfig"];
export const applyChutesConfig: FacadeModule["applyChutesConfig"] = ((...args) =>
  loadFacadeModule()["applyChutesConfig"](...args)) as FacadeModule["applyChutesConfig"];
export const applyChutesProviderConfig: FacadeModule["applyChutesProviderConfig"] = ((...args) =>
  loadFacadeModule()["applyChutesProviderConfig"](
    ...args,
  )) as FacadeModule["applyChutesProviderConfig"];
export const buildChutesModelDefinition: FacadeModule["buildChutesModelDefinition"] = ((...args) =>
  loadFacadeModule()["buildChutesModelDefinition"](
    ...args,
  )) as FacadeModule["buildChutesModelDefinition"];
export const buildChutesProvider: FacadeModule["buildChutesProvider"] = ((...args) =>
  loadFacadeModule()["buildChutesProvider"](...args)) as FacadeModule["buildChutesProvider"];
export const CHUTES_BASE_URL: FacadeModule["CHUTES_BASE_URL"] =
  loadFacadeModule()["CHUTES_BASE_URL"];
export const CHUTES_DEFAULT_MODEL_ID: FacadeModule["CHUTES_DEFAULT_MODEL_ID"] =
  loadFacadeModule()["CHUTES_DEFAULT_MODEL_ID"];
export const CHUTES_DEFAULT_MODEL_REF: FacadeModule["CHUTES_DEFAULT_MODEL_REF"] =
  loadFacadeModule()["CHUTES_DEFAULT_MODEL_REF"];
export const CHUTES_MODEL_CATALOG: FacadeModule["CHUTES_MODEL_CATALOG"] =
  createLazyFacadeArrayValue(
    () => loadFacadeModule()["CHUTES_MODEL_CATALOG"] as unknown as readonly unknown[],
  ) as FacadeModule["CHUTES_MODEL_CATALOG"];
export const discoverChutesModels: FacadeModule["discoverChutesModels"] = ((...args) =>
  loadFacadeModule()["discoverChutesModels"](...args)) as FacadeModule["discoverChutesModels"];
