// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["cloudflare-ai-gateway"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "cloudflare-ai-gateway",
    artifactBasename: "api.js",
  });
}
export const applyCloudflareAiGatewayConfig: FacadeModule["applyCloudflareAiGatewayConfig"] = ((
  ...args
) =>
  loadFacadeModule()["applyCloudflareAiGatewayConfig"](
    ...args,
  )) as FacadeModule["applyCloudflareAiGatewayConfig"];
export const applyCloudflareAiGatewayProviderConfig: FacadeModule["applyCloudflareAiGatewayProviderConfig"] =
  ((...args) =>
    loadFacadeModule()["applyCloudflareAiGatewayProviderConfig"](
      ...args,
    )) as FacadeModule["applyCloudflareAiGatewayProviderConfig"];
export const buildCloudflareAiGatewayConfigPatch: FacadeModule["buildCloudflareAiGatewayConfigPatch"] =
  ((...args) =>
    loadFacadeModule()["buildCloudflareAiGatewayConfigPatch"](
      ...args,
    )) as FacadeModule["buildCloudflareAiGatewayConfigPatch"];
export const buildCloudflareAiGatewayModelDefinition: FacadeModule["buildCloudflareAiGatewayModelDefinition"] =
  ((...args) =>
    loadFacadeModule()["buildCloudflareAiGatewayModelDefinition"](
      ...args,
    )) as FacadeModule["buildCloudflareAiGatewayModelDefinition"];
export const CLOUDFLARE_AI_GATEWAY_DEFAULT_MODEL_ID: FacadeModule["CLOUDFLARE_AI_GATEWAY_DEFAULT_MODEL_ID"] =
  loadFacadeModule()["CLOUDFLARE_AI_GATEWAY_DEFAULT_MODEL_ID"];
export const CLOUDFLARE_AI_GATEWAY_DEFAULT_MODEL_REF: FacadeModule["CLOUDFLARE_AI_GATEWAY_DEFAULT_MODEL_REF"] =
  loadFacadeModule()["CLOUDFLARE_AI_GATEWAY_DEFAULT_MODEL_REF"];
export const CLOUDFLARE_AI_GATEWAY_PROVIDER_ID: FacadeModule["CLOUDFLARE_AI_GATEWAY_PROVIDER_ID"] =
  loadFacadeModule()["CLOUDFLARE_AI_GATEWAY_PROVIDER_ID"];
export const resolveCloudflareAiGatewayBaseUrl: FacadeModule["resolveCloudflareAiGatewayBaseUrl"] =
  ((...args) =>
    loadFacadeModule()["resolveCloudflareAiGatewayBaseUrl"](
      ...args,
    )) as FacadeModule["resolveCloudflareAiGatewayBaseUrl"];
