// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  applyCloudflareAiGatewayConfig,
  applyCloudflareAiGatewayProviderConfig,
  buildCloudflareAiGatewayConfigPatch,
  buildCloudflareAiGatewayModelDefinition,
  CLOUDFLARE_AI_GATEWAY_DEFAULT_MODEL_ID,
  CLOUDFLARE_AI_GATEWAY_DEFAULT_MODEL_REF,
  CLOUDFLARE_AI_GATEWAY_PROVIDER_ID,
  resolveCloudflareAiGatewayBaseUrl,
} from "../../extensions/cloudflare-ai-gateway/api.js";
