// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["deepseek"];
type FacadeModule = FacadeEntry["module"];
import {
  createLazyFacadeArrayValue,
  loadBundledPluginPublicSurfaceModuleSync,
} from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "deepseek",
    artifactBasename: "api.js",
  });
}
export const buildDeepSeekModelDefinition: FacadeModule["buildDeepSeekModelDefinition"] = ((
  ...args
) =>
  loadFacadeModule()["buildDeepSeekModelDefinition"](
    ...args,
  )) as FacadeModule["buildDeepSeekModelDefinition"];
export const buildDeepSeekProvider: FacadeModule["buildDeepSeekProvider"] = ((...args) =>
  loadFacadeModule()["buildDeepSeekProvider"](...args)) as FacadeModule["buildDeepSeekProvider"];
export const DEEPSEEK_BASE_URL: FacadeModule["DEEPSEEK_BASE_URL"] =
  loadFacadeModule()["DEEPSEEK_BASE_URL"];
export const DEEPSEEK_MODEL_CATALOG: FacadeModule["DEEPSEEK_MODEL_CATALOG"] =
  createLazyFacadeArrayValue(
    () => loadFacadeModule()["DEEPSEEK_MODEL_CATALOG"] as unknown as readonly unknown[],
  ) as FacadeModule["DEEPSEEK_MODEL_CATALOG"];
