// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  buildDeepSeekModelDefinition,
  buildDeepSeekProvider,
  DEEPSEEK_BASE_URL,
  DEEPSEEK_MODEL_CATALOG,
} from "../../extensions/deepseek/api.js";
