// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export { resolveDiscordAccount } from "../../extensions/discord/api.js";
export type { ResolvedDiscordAccount } from "../../extensions/discord/api.js";
