// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["discord-runtime-surface"];
type FacadeModule = FacadeEntry["module"];
import {
  createLazyFacadeObjectValue,
  loadBundledPluginPublicSurfaceModuleSync,
} from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "discord",
    artifactBasename: "runtime-api.js",
  });
}
export const addRoleDiscord: FacadeModule["addRoleDiscord"] = ((...args) =>
  loadFacadeModule()["addRoleDiscord"](...args)) as FacadeModule["addRoleDiscord"];
export const auditDiscordChannelPermissions: FacadeModule["auditDiscordChannelPermissions"] = ((
  ...args
) =>
  loadFacadeModule()["auditDiscordChannelPermissions"](
    ...args,
  )) as FacadeModule["auditDiscordChannelPermissions"];
export const banMemberDiscord: FacadeModule["banMemberDiscord"] = ((...args) =>
  loadFacadeModule()["banMemberDiscord"](...args)) as FacadeModule["banMemberDiscord"];
export const collectDiscordAuditChannelIds: FacadeModule["collectDiscordAuditChannelIds"] = ((
  ...args
) =>
  loadFacadeModule()["collectDiscordAuditChannelIds"](
    ...args,
  )) as FacadeModule["collectDiscordAuditChannelIds"];
export const createChannelDiscord: FacadeModule["createChannelDiscord"] = ((...args) =>
  loadFacadeModule()["createChannelDiscord"](...args)) as FacadeModule["createChannelDiscord"];
export const createScheduledEventDiscord: FacadeModule["createScheduledEventDiscord"] = ((
  ...args
) =>
  loadFacadeModule()["createScheduledEventDiscord"](
    ...args,
  )) as FacadeModule["createScheduledEventDiscord"];
export const createThreadDiscord: FacadeModule["createThreadDiscord"] = ((...args) =>
  loadFacadeModule()["createThreadDiscord"](...args)) as FacadeModule["createThreadDiscord"];
export const deleteChannelDiscord: FacadeModule["deleteChannelDiscord"] = ((...args) =>
  loadFacadeModule()["deleteChannelDiscord"](...args)) as FacadeModule["deleteChannelDiscord"];
export const deleteMessageDiscord: FacadeModule["deleteMessageDiscord"] = ((...args) =>
  loadFacadeModule()["deleteMessageDiscord"](...args)) as FacadeModule["deleteMessageDiscord"];
export const discordMessageActions: FacadeModule["discordMessageActions"] =
  createLazyFacadeObjectValue(
    () => loadFacadeModule()["discordMessageActions"] as object,
  ) as FacadeModule["discordMessageActions"];
export const editChannelDiscord: FacadeModule["editChannelDiscord"] = ((...args) =>
  loadFacadeModule()["editChannelDiscord"](...args)) as FacadeModule["editChannelDiscord"];
export const editDiscordComponentMessage: FacadeModule["editDiscordComponentMessage"] = ((
  ...args
) =>
  loadFacadeModule()["editDiscordComponentMessage"](
    ...args,
  )) as FacadeModule["editDiscordComponentMessage"];
export const editMessageDiscord: FacadeModule["editMessageDiscord"] = ((...args) =>
  loadFacadeModule()["editMessageDiscord"](...args)) as FacadeModule["editMessageDiscord"];
export const fetchChannelInfoDiscord: FacadeModule["fetchChannelInfoDiscord"] = ((...args) =>
  loadFacadeModule()["fetchChannelInfoDiscord"](
    ...args,
  )) as FacadeModule["fetchChannelInfoDiscord"];
export const fetchChannelPermissionsDiscord: FacadeModule["fetchChannelPermissionsDiscord"] = ((
  ...args
) =>
  loadFacadeModule()["fetchChannelPermissionsDiscord"](
    ...args,
  )) as FacadeModule["fetchChannelPermissionsDiscord"];
export const fetchMemberInfoDiscord: FacadeModule["fetchMemberInfoDiscord"] = ((...args) =>
  loadFacadeModule()["fetchMemberInfoDiscord"](...args)) as FacadeModule["fetchMemberInfoDiscord"];
export const fetchMessageDiscord: FacadeModule["fetchMessageDiscord"] = ((...args) =>
  loadFacadeModule()["fetchMessageDiscord"](...args)) as FacadeModule["fetchMessageDiscord"];
export const fetchReactionsDiscord: FacadeModule["fetchReactionsDiscord"] = ((...args) =>
  loadFacadeModule()["fetchReactionsDiscord"](...args)) as FacadeModule["fetchReactionsDiscord"];
export const fetchRoleInfoDiscord: FacadeModule["fetchRoleInfoDiscord"] = ((...args) =>
  loadFacadeModule()["fetchRoleInfoDiscord"](...args)) as FacadeModule["fetchRoleInfoDiscord"];
export const fetchVoiceStatusDiscord: FacadeModule["fetchVoiceStatusDiscord"] = ((...args) =>
  loadFacadeModule()["fetchVoiceStatusDiscord"](
    ...args,
  )) as FacadeModule["fetchVoiceStatusDiscord"];
export const getGateway: FacadeModule["getGateway"] = ((...args) =>
  loadFacadeModule()["getGateway"](...args)) as FacadeModule["getGateway"];
export const getPresence: FacadeModule["getPresence"] = ((...args) =>
  loadFacadeModule()["getPresence"](...args)) as FacadeModule["getPresence"];
export const hasAnyGuildPermissionDiscord: FacadeModule["hasAnyGuildPermissionDiscord"] = ((
  ...args
) =>
  loadFacadeModule()["hasAnyGuildPermissionDiscord"](
    ...args,
  )) as FacadeModule["hasAnyGuildPermissionDiscord"];
export const kickMemberDiscord: FacadeModule["kickMemberDiscord"] = ((...args) =>
  loadFacadeModule()["kickMemberDiscord"](...args)) as FacadeModule["kickMemberDiscord"];
export const listDiscordDirectoryGroupsLive: FacadeModule["listDiscordDirectoryGroupsLive"] = ((
  ...args
) =>
  loadFacadeModule()["listDiscordDirectoryGroupsLive"](
    ...args,
  )) as FacadeModule["listDiscordDirectoryGroupsLive"];
export const listDiscordDirectoryPeersLive: FacadeModule["listDiscordDirectoryPeersLive"] = ((
  ...args
) =>
  loadFacadeModule()["listDiscordDirectoryPeersLive"](
    ...args,
  )) as FacadeModule["listDiscordDirectoryPeersLive"];
export const listGuildChannelsDiscord: FacadeModule["listGuildChannelsDiscord"] = ((...args) =>
  loadFacadeModule()["listGuildChannelsDiscord"](
    ...args,
  )) as FacadeModule["listGuildChannelsDiscord"];
export const listGuildEmojisDiscord: FacadeModule["listGuildEmojisDiscord"] = ((...args) =>
  loadFacadeModule()["listGuildEmojisDiscord"](...args)) as FacadeModule["listGuildEmojisDiscord"];
export const listPinsDiscord: FacadeModule["listPinsDiscord"] = ((...args) =>
  loadFacadeModule()["listPinsDiscord"](...args)) as FacadeModule["listPinsDiscord"];
export const listScheduledEventsDiscord: FacadeModule["listScheduledEventsDiscord"] = ((...args) =>
  loadFacadeModule()["listScheduledEventsDiscord"](
    ...args,
  )) as FacadeModule["listScheduledEventsDiscord"];
export const listThreadsDiscord: FacadeModule["listThreadsDiscord"] = ((...args) =>
  loadFacadeModule()["listThreadsDiscord"](...args)) as FacadeModule["listThreadsDiscord"];
export const monitorDiscordProvider: FacadeModule["monitorDiscordProvider"] = ((...args) =>
  loadFacadeModule()["monitorDiscordProvider"](...args)) as FacadeModule["monitorDiscordProvider"];
export const moveChannelDiscord: FacadeModule["moveChannelDiscord"] = ((...args) =>
  loadFacadeModule()["moveChannelDiscord"](...args)) as FacadeModule["moveChannelDiscord"];
export const pinMessageDiscord: FacadeModule["pinMessageDiscord"] = ((...args) =>
  loadFacadeModule()["pinMessageDiscord"](...args)) as FacadeModule["pinMessageDiscord"];
export const probeDiscord: FacadeModule["probeDiscord"] = ((...args) =>
  loadFacadeModule()["probeDiscord"](...args)) as FacadeModule["probeDiscord"];
export const reactMessageDiscord: FacadeModule["reactMessageDiscord"] = ((...args) =>
  loadFacadeModule()["reactMessageDiscord"](...args)) as FacadeModule["reactMessageDiscord"];
export const readMessagesDiscord: FacadeModule["readMessagesDiscord"] = ((...args) =>
  loadFacadeModule()["readMessagesDiscord"](...args)) as FacadeModule["readMessagesDiscord"];
export const registerBuiltDiscordComponentMessage: FacadeModule["registerBuiltDiscordComponentMessage"] =
  ((...args) =>
    loadFacadeModule()["registerBuiltDiscordComponentMessage"](
      ...args,
    )) as FacadeModule["registerBuiltDiscordComponentMessage"];
export const removeChannelPermissionDiscord: FacadeModule["removeChannelPermissionDiscord"] = ((
  ...args
) =>
  loadFacadeModule()["removeChannelPermissionDiscord"](
    ...args,
  )) as FacadeModule["removeChannelPermissionDiscord"];
export const removeOwnReactionsDiscord: FacadeModule["removeOwnReactionsDiscord"] = ((...args) =>
  loadFacadeModule()["removeOwnReactionsDiscord"](
    ...args,
  )) as FacadeModule["removeOwnReactionsDiscord"];
export const removeReactionDiscord: FacadeModule["removeReactionDiscord"] = ((...args) =>
  loadFacadeModule()["removeReactionDiscord"](...args)) as FacadeModule["removeReactionDiscord"];
export const removeRoleDiscord: FacadeModule["removeRoleDiscord"] = ((...args) =>
  loadFacadeModule()["removeRoleDiscord"](...args)) as FacadeModule["removeRoleDiscord"];
export const resolveDiscordChannelAllowlist: FacadeModule["resolveDiscordChannelAllowlist"] = ((
  ...args
) =>
  loadFacadeModule()["resolveDiscordChannelAllowlist"](
    ...args,
  )) as FacadeModule["resolveDiscordChannelAllowlist"];
export const resolveDiscordOutboundSessionRoute: FacadeModule["resolveDiscordOutboundSessionRoute"] =
  ((...args) =>
    loadFacadeModule()["resolveDiscordOutboundSessionRoute"](
      ...args,
    )) as FacadeModule["resolveDiscordOutboundSessionRoute"];
export const resolveDiscordUserAllowlist: FacadeModule["resolveDiscordUserAllowlist"] = ((
  ...args
) =>
  loadFacadeModule()["resolveDiscordUserAllowlist"](
    ...args,
  )) as FacadeModule["resolveDiscordUserAllowlist"];
export const searchMessagesDiscord: FacadeModule["searchMessagesDiscord"] = ((...args) =>
  loadFacadeModule()["searchMessagesDiscord"](...args)) as FacadeModule["searchMessagesDiscord"];
export const sendDiscordComponentMessage: FacadeModule["sendDiscordComponentMessage"] = ((
  ...args
) =>
  loadFacadeModule()["sendDiscordComponentMessage"](
    ...args,
  )) as FacadeModule["sendDiscordComponentMessage"];
export const sendMessageDiscord: FacadeModule["sendMessageDiscord"] = ((...args) =>
  loadFacadeModule()["sendMessageDiscord"](...args)) as FacadeModule["sendMessageDiscord"];
export const sendPollDiscord: FacadeModule["sendPollDiscord"] = ((...args) =>
  loadFacadeModule()["sendPollDiscord"](...args)) as FacadeModule["sendPollDiscord"];
export const sendStickerDiscord: FacadeModule["sendStickerDiscord"] = ((...args) =>
  loadFacadeModule()["sendStickerDiscord"](...args)) as FacadeModule["sendStickerDiscord"];
export const sendTypingDiscord: FacadeModule["sendTypingDiscord"] = ((...args) =>
  loadFacadeModule()["sendTypingDiscord"](...args)) as FacadeModule["sendTypingDiscord"];
export const sendVoiceMessageDiscord: FacadeModule["sendVoiceMessageDiscord"] = ((...args) =>
  loadFacadeModule()["sendVoiceMessageDiscord"](
    ...args,
  )) as FacadeModule["sendVoiceMessageDiscord"];
export const setChannelPermissionDiscord: FacadeModule["setChannelPermissionDiscord"] = ((
  ...args
) =>
  loadFacadeModule()["setChannelPermissionDiscord"](
    ...args,
  )) as FacadeModule["setChannelPermissionDiscord"];
export const timeoutMemberDiscord: FacadeModule["timeoutMemberDiscord"] = ((...args) =>
  loadFacadeModule()["timeoutMemberDiscord"](...args)) as FacadeModule["timeoutMemberDiscord"];
export const unpinMessageDiscord: FacadeModule["unpinMessageDiscord"] = ((...args) =>
  loadFacadeModule()["unpinMessageDiscord"](...args)) as FacadeModule["unpinMessageDiscord"];
export const uploadEmojiDiscord: FacadeModule["uploadEmojiDiscord"] = ((...args) =>
  loadFacadeModule()["uploadEmojiDiscord"](...args)) as FacadeModule["uploadEmojiDiscord"];
export const uploadStickerDiscord: FacadeModule["uploadStickerDiscord"] = ((...args) =>
  loadFacadeModule()["uploadStickerDiscord"](...args)) as FacadeModule["uploadStickerDiscord"];
