// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["discord-thread-bindings"];
type FacadeModule = FacadeEntry["module"];
export { unbindThreadBindingsBySessionKey } from "./discord-maintenance.js";
import { loadActivatedBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadActivatedBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "discord",
    artifactBasename: "runtime-api.js",
  });
}
export const autoBindSpawnedDiscordSubagent: FacadeModule["autoBindSpawnedDiscordSubagent"] = ((
  ...args
) =>
  loadFacadeModule()["autoBindSpawnedDiscordSubagent"](
    ...args,
  )) as FacadeModule["autoBindSpawnedDiscordSubagent"];
export const createThreadBindingManager: FacadeModule["createThreadBindingManager"] = ((...args) =>
  loadFacadeModule()["createThreadBindingManager"](
    ...args,
  )) as FacadeModule["createThreadBindingManager"];
export const getThreadBindingManager: FacadeModule["getThreadBindingManager"] = ((...args) =>
  loadFacadeModule()["getThreadBindingManager"](
    ...args,
  )) as FacadeModule["getThreadBindingManager"];
export const listThreadBindingsBySessionKey: FacadeModule["listThreadBindingsBySessionKey"] = ((
  ...args
) =>
  loadFacadeModule()["listThreadBindingsBySessionKey"](
    ...args,
  )) as FacadeModule["listThreadBindingsBySessionKey"];
export const resolveThreadBindingIdleTimeoutMs: FacadeModule["resolveThreadBindingIdleTimeoutMs"] =
  ((...args) =>
    loadFacadeModule()["resolveThreadBindingIdleTimeoutMs"](
      ...args,
    )) as FacadeModule["resolveThreadBindingIdleTimeoutMs"];
export const resolveThreadBindingInactivityExpiresAt: FacadeModule["resolveThreadBindingInactivityExpiresAt"] =
  ((...args) =>
    loadFacadeModule()["resolveThreadBindingInactivityExpiresAt"](
      ...args,
    )) as FacadeModule["resolveThreadBindingInactivityExpiresAt"];
export const resolveThreadBindingMaxAgeExpiresAt: FacadeModule["resolveThreadBindingMaxAgeExpiresAt"] =
  ((...args) =>
    loadFacadeModule()["resolveThreadBindingMaxAgeExpiresAt"](
      ...args,
    )) as FacadeModule["resolveThreadBindingMaxAgeExpiresAt"];
export const resolveThreadBindingMaxAgeMs: FacadeModule["resolveThreadBindingMaxAgeMs"] = ((
  ...args
) =>
  loadFacadeModule()["resolveThreadBindingMaxAgeMs"](
    ...args,
  )) as FacadeModule["resolveThreadBindingMaxAgeMs"];
export const setThreadBindingIdleTimeoutBySessionKey: FacadeModule["setThreadBindingIdleTimeoutBySessionKey"] =
  ((...args) =>
    loadFacadeModule()["setThreadBindingIdleTimeoutBySessionKey"](
      ...args,
    )) as FacadeModule["setThreadBindingIdleTimeoutBySessionKey"];
export const setThreadBindingMaxAgeBySessionKey: FacadeModule["setThreadBindingMaxAgeBySessionKey"] =
  ((...args) =>
    loadFacadeModule()["setThreadBindingMaxAgeBySessionKey"](
      ...args,
    )) as FacadeModule["setThreadBindingMaxAgeBySessionKey"];
export type ThreadBindingManager = FacadeEntry["types"]["ThreadBindingManager"];
export type ThreadBindingRecord = FacadeEntry["types"]["ThreadBindingRecord"];
export type ThreadBindingTargetKind = FacadeEntry["types"]["ThreadBindingTargetKind"];
