// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["discord-surface"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "discord",
    artifactBasename: "api.js",
  });
}
export const buildDiscordComponentMessage: FacadeModule["buildDiscordComponentMessage"] = ((
  ...args
) =>
  loadFacadeModule()["buildDiscordComponentMessage"](
    ...args,
  )) as FacadeModule["buildDiscordComponentMessage"];
export const collectDiscordStatusIssues: FacadeModule["collectDiscordStatusIssues"] = ((...args) =>
  loadFacadeModule()["collectDiscordStatusIssues"](
    ...args,
  )) as FacadeModule["collectDiscordStatusIssues"];
export const createDiscordActionGate: FacadeModule["createDiscordActionGate"] = ((...args) =>
  loadFacadeModule()["createDiscordActionGate"](
    ...args,
  )) as FacadeModule["createDiscordActionGate"];
export const handleDiscordMessageAction: FacadeModule["handleDiscordMessageAction"] = ((...args) =>
  loadFacadeModule()["handleDiscordMessageAction"](
    ...args,
  )) as FacadeModule["handleDiscordMessageAction"];
export const inspectDiscordAccount: FacadeModule["inspectDiscordAccount"] = ((...args) =>
  loadFacadeModule()["inspectDiscordAccount"](...args)) as FacadeModule["inspectDiscordAccount"];
export const isDiscordExecApprovalApprover: FacadeModule["isDiscordExecApprovalApprover"] = ((
  ...args
) =>
  loadFacadeModule()["isDiscordExecApprovalApprover"](
    ...args,
  )) as FacadeModule["isDiscordExecApprovalApprover"];
export const isDiscordExecApprovalClientEnabled: FacadeModule["isDiscordExecApprovalClientEnabled"] =
  ((...args) =>
    loadFacadeModule()["isDiscordExecApprovalClientEnabled"](
      ...args,
    )) as FacadeModule["isDiscordExecApprovalClientEnabled"];
export const listDiscordAccountIds: FacadeModule["listDiscordAccountIds"] = ((...args) =>
  loadFacadeModule()["listDiscordAccountIds"](...args)) as FacadeModule["listDiscordAccountIds"];
export const listDiscordDirectoryGroupsFromConfig: FacadeModule["listDiscordDirectoryGroupsFromConfig"] =
  ((...args) =>
    loadFacadeModule()["listDiscordDirectoryGroupsFromConfig"](
      ...args,
    )) as FacadeModule["listDiscordDirectoryGroupsFromConfig"];
export const listDiscordDirectoryPeersFromConfig: FacadeModule["listDiscordDirectoryPeersFromConfig"] =
  ((...args) =>
    loadFacadeModule()["listDiscordDirectoryPeersFromConfig"](
      ...args,
    )) as FacadeModule["listDiscordDirectoryPeersFromConfig"];
export const looksLikeDiscordTargetId: FacadeModule["looksLikeDiscordTargetId"] = ((...args) =>
  loadFacadeModule()["looksLikeDiscordTargetId"](
    ...args,
  )) as FacadeModule["looksLikeDiscordTargetId"];
export const normalizeDiscordMessagingTarget: FacadeModule["normalizeDiscordMessagingTarget"] = ((
  ...args
) =>
  loadFacadeModule()["normalizeDiscordMessagingTarget"](
    ...args,
  )) as FacadeModule["normalizeDiscordMessagingTarget"];
export const normalizeDiscordOutboundTarget: FacadeModule["normalizeDiscordOutboundTarget"] = ((
  ...args
) =>
  loadFacadeModule()["normalizeDiscordOutboundTarget"](
    ...args,
  )) as FacadeModule["normalizeDiscordOutboundTarget"];
export const readDiscordComponentSpec: FacadeModule["readDiscordComponentSpec"] = ((...args) =>
  loadFacadeModule()["readDiscordComponentSpec"](
    ...args,
  )) as FacadeModule["readDiscordComponentSpec"];
export const resolveDefaultDiscordAccountId: FacadeModule["resolveDefaultDiscordAccountId"] = ((
  ...args
) =>
  loadFacadeModule()["resolveDefaultDiscordAccountId"](
    ...args,
  )) as FacadeModule["resolveDefaultDiscordAccountId"];
export const resolveDiscordAccount: FacadeModule["resolveDiscordAccount"] = ((...args) =>
  loadFacadeModule()["resolveDiscordAccount"](...args)) as FacadeModule["resolveDiscordAccount"];
export const resolveDiscordChannelId: FacadeModule["resolveDiscordChannelId"] = ((...args) =>
  loadFacadeModule()["resolveDiscordChannelId"](
    ...args,
  )) as FacadeModule["resolveDiscordChannelId"];
export const resolveDiscordRuntimeGroupPolicy: FacadeModule["resolveDiscordRuntimeGroupPolicy"] = ((
  ...args
) =>
  loadFacadeModule()["resolveDiscordRuntimeGroupPolicy"](
    ...args,
  )) as FacadeModule["resolveDiscordRuntimeGroupPolicy"];
export const resolveDiscordGroupRequireMention: FacadeModule["resolveDiscordGroupRequireMention"] =
  ((...args) =>
    loadFacadeModule()["resolveDiscordGroupRequireMention"](
      ...args,
    )) as FacadeModule["resolveDiscordGroupRequireMention"];
export const resolveDiscordGroupToolPolicy: FacadeModule["resolveDiscordGroupToolPolicy"] = ((
  ...args
) =>
  loadFacadeModule()["resolveDiscordGroupToolPolicy"](
    ...args,
  )) as FacadeModule["resolveDiscordGroupToolPolicy"];
export type DiscordComponentMessageSpec = FacadeEntry["types"]["DiscordComponentMessageSpec"];
export type DiscordProbe = FacadeEntry["types"]["DiscordProbe"];
export type DiscordSendComponents = FacadeEntry["types"]["DiscordSendComponents"];
export type DiscordSendEmbeds = FacadeEntry["types"]["DiscordSendEmbeds"];
export type DiscordSendResult = FacadeEntry["types"]["DiscordSendResult"];
export type DiscordTokenResolution = FacadeEntry["types"]["DiscordTokenResolution"];
export type InspectedDiscordAccount = FacadeEntry["types"]["InspectedDiscordAccount"];
export type ResolvedDiscordAccount = FacadeEntry["types"]["ResolvedDiscordAccount"];
