// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["discord-session-key"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "discord",
    artifactBasename: "session-key-api.js",
  });
}
export const normalizeExplicitDiscordSessionKey: FacadeModule["normalizeExplicitDiscordSessionKey"] =
  ((...args) =>
    loadFacadeModule()["normalizeExplicitDiscordSessionKey"](
      ...args,
    )) as FacadeModule["normalizeExplicitDiscordSessionKey"];
