// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["discord-account"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "discord",
    artifactBasename: "api.js",
  });
}
export const resolveDiscordAccount: FacadeModule["resolveDiscordAccount"] = ((...args) =>
  loadFacadeModule()["resolveDiscordAccount"](...args)) as FacadeModule["resolveDiscordAccount"];
export type ResolvedDiscordAccount = FacadeEntry["types"]["ResolvedDiscordAccount"];
