// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["discord-timeouts"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "discord",
    artifactBasename: "timeouts.js",
  });
}
export const DISCORD_DEFAULT_INBOUND_WORKER_TIMEOUT_MS: FacadeModule["DISCORD_DEFAULT_INBOUND_WORKER_TIMEOUT_MS"] =
  loadFacadeModule()["DISCORD_DEFAULT_INBOUND_WORKER_TIMEOUT_MS"];
export const DISCORD_DEFAULT_LISTENER_TIMEOUT_MS: FacadeModule["DISCORD_DEFAULT_LISTENER_TIMEOUT_MS"] =
  loadFacadeModule()["DISCORD_DEFAULT_LISTENER_TIMEOUT_MS"];
