// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  buildFeishuConversationId,
  createFeishuThreadBindingManager,
  feishuSessionBindingAdapterChannels,
  feishuThreadBindingTesting,
  parseFeishuDirectConversationId,
  parseFeishuConversationId,
  parseFeishuTargetId,
} from "../../extensions/feishu/api.js";
