// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["huggingface"];
type FacadeModule = FacadeEntry["module"];
import {
  createLazyFacadeArrayValue,
  loadBundledPluginPublicSurfaceModuleSync,
} from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "huggingface",
    artifactBasename: "api.js",
  });
}
export const buildHuggingfaceModelDefinition: FacadeModule["buildHuggingfaceModelDefinition"] = ((
  ...args
) =>
  loadFacadeModule()["buildHuggingfaceModelDefinition"](
    ...args,
  )) as FacadeModule["buildHuggingfaceModelDefinition"];
export const buildHuggingfaceProvider: FacadeModule["buildHuggingfaceProvider"] = ((...args) =>
  loadFacadeModule()["buildHuggingfaceProvider"](
    ...args,
  )) as FacadeModule["buildHuggingfaceProvider"];
export const discoverHuggingfaceModels: FacadeModule["discoverHuggingfaceModels"] = ((...args) =>
  loadFacadeModule()["discoverHuggingfaceModels"](
    ...args,
  )) as FacadeModule["discoverHuggingfaceModels"];
export const HUGGINGFACE_BASE_URL: FacadeModule["HUGGINGFACE_BASE_URL"] =
  loadFacadeModule()["HUGGINGFACE_BASE_URL"];
export const HUGGINGFACE_DEFAULT_MODEL_REF: FacadeModule["HUGGINGFACE_DEFAULT_MODEL_REF"] =
  loadFacadeModule()["HUGGINGFACE_DEFAULT_MODEL_REF"];
export const HUGGINGFACE_MODEL_CATALOG: FacadeModule["HUGGINGFACE_MODEL_CATALOG"] =
  createLazyFacadeArrayValue(
    () => loadFacadeModule()["HUGGINGFACE_MODEL_CATALOG"] as unknown as readonly unknown[],
  ) as FacadeModule["HUGGINGFACE_MODEL_CATALOG"];
export const HUGGINGFACE_POLICY_SUFFIXES: FacadeModule["HUGGINGFACE_POLICY_SUFFIXES"] =
  createLazyFacadeArrayValue(
    () => loadFacadeModule()["HUGGINGFACE_POLICY_SUFFIXES"] as unknown as readonly unknown[],
  ) as FacadeModule["HUGGINGFACE_POLICY_SUFFIXES"];
export const isHuggingfacePolicyLocked: FacadeModule["isHuggingfacePolicyLocked"] = ((...args) =>
  loadFacadeModule()["isHuggingfacePolicyLocked"](
    ...args,
  )) as FacadeModule["isHuggingfacePolicyLocked"];
