// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["image-generation-runtime"];
type FacadeModule = FacadeEntry["module"];
import { loadActivatedBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadActivatedBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "image-generation-core",
    artifactBasename: "runtime-api.js",
  });
}
export const generateImage: FacadeModule["generateImage"] = ((...args) =>
  loadFacadeModule()["generateImage"](...args)) as FacadeModule["generateImage"];
export const listRuntimeImageGenerationProviders: FacadeModule["listRuntimeImageGenerationProviders"] =
  ((...args) =>
    loadFacadeModule()["listRuntimeImageGenerationProviders"](
      ...args,
    )) as FacadeModule["listRuntimeImageGenerationProviders"];
export type GenerateImageParams = FacadeEntry["types"]["GenerateImageParams"];
export type GenerateImageRuntimeResult = FacadeEntry["types"]["GenerateImageRuntimeResult"];
