// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  normalizeIMessageHandle,
  parseChatAllowTargetPrefixes,
  parseChatTargetPrefixesOrThrow,
  resolveServicePrefixedAllowTarget,
  resolveServicePrefixedTarget,
} from "../../extensions/imessage/api.js";
export type { ParsedChatTarget } from "../../extensions/imessage/api.js";
