// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  monitorIMessageProvider,
  probeIMessage,
  sendMessageIMessage,
} from "../../extensions/imessage/runtime-api.js";
export type { IMessageProbe } from "../../extensions/imessage/runtime-api.js";
