// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  normalizeIMessageHandle,
  resolveIMessageRuntimeGroupPolicy,
  resolveIMessageGroupRequireMention,
  resolveIMessageGroupToolPolicy,
} from "../../extensions/imessage/api.js";
