// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  ircSetupAdapter,
  ircSetupWizard,
  listIrcAccountIds,
  resolveDefaultIrcAccountId,
  resolveIrcAccount,
} from "../../extensions/irc/api.js";
