// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["kilocode"];
type FacadeModule = FacadeEntry["module"];
import {
  createLazyFacadeObjectValue,
  createLazyFacadeArrayValue,
  loadBundledPluginPublicSurfaceModuleSync,
} from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "kilocode",
    artifactBasename: "api.js",
  });
}
export const buildKilocodeProvider: FacadeModule["buildKilocodeProvider"] = ((...args) =>
  loadFacadeModule()["buildKilocodeProvider"](...args)) as FacadeModule["buildKilocodeProvider"];
export const buildKilocodeProviderWithDiscovery: FacadeModule["buildKilocodeProviderWithDiscovery"] =
  ((...args) =>
    loadFacadeModule()["buildKilocodeProviderWithDiscovery"](
      ...args,
    )) as FacadeModule["buildKilocodeProviderWithDiscovery"];
export const buildKilocodeModelDefinition: FacadeModule["buildKilocodeModelDefinition"] = ((
  ...args
) =>
  loadFacadeModule()["buildKilocodeModelDefinition"](
    ...args,
  )) as FacadeModule["buildKilocodeModelDefinition"];
export const discoverKilocodeModels: FacadeModule["discoverKilocodeModels"] = ((...args) =>
  loadFacadeModule()["discoverKilocodeModels"](...args)) as FacadeModule["discoverKilocodeModels"];
export const KILOCODE_BASE_URL: FacadeModule["KILOCODE_BASE_URL"] =
  loadFacadeModule()["KILOCODE_BASE_URL"];
export const KILOCODE_DEFAULT_CONTEXT_WINDOW: FacadeModule["KILOCODE_DEFAULT_CONTEXT_WINDOW"] =
  loadFacadeModule()["KILOCODE_DEFAULT_CONTEXT_WINDOW"];
export const KILOCODE_DEFAULT_COST: FacadeModule["KILOCODE_DEFAULT_COST"] =
  createLazyFacadeObjectValue(
    () => loadFacadeModule()["KILOCODE_DEFAULT_COST"] as object,
  ) as FacadeModule["KILOCODE_DEFAULT_COST"];
export const KILOCODE_DEFAULT_MAX_TOKENS: FacadeModule["KILOCODE_DEFAULT_MAX_TOKENS"] =
  loadFacadeModule()["KILOCODE_DEFAULT_MAX_TOKENS"];
export const KILOCODE_DEFAULT_MODEL_ID: FacadeModule["KILOCODE_DEFAULT_MODEL_ID"] =
  loadFacadeModule()["KILOCODE_DEFAULT_MODEL_ID"];
export const KILOCODE_DEFAULT_MODEL_NAME: FacadeModule["KILOCODE_DEFAULT_MODEL_NAME"] =
  loadFacadeModule()["KILOCODE_DEFAULT_MODEL_NAME"];
export const KILOCODE_DEFAULT_MODEL_REF: FacadeModule["KILOCODE_DEFAULT_MODEL_REF"] =
  loadFacadeModule()["KILOCODE_DEFAULT_MODEL_REF"];
export const KILOCODE_MODELS_URL: FacadeModule["KILOCODE_MODELS_URL"] =
  loadFacadeModule()["KILOCODE_MODELS_URL"];
export const KILOCODE_MODEL_CATALOG: FacadeModule["KILOCODE_MODEL_CATALOG"] =
  createLazyFacadeArrayValue(
    () => loadFacadeModule()["KILOCODE_MODEL_CATALOG"] as unknown as readonly unknown[],
  ) as FacadeModule["KILOCODE_MODEL_CATALOG"];
