// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["kimi-coding"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "kimi-coding",
    artifactBasename: "api.js",
  });
}
export const buildKimiCodingProvider: FacadeModule["buildKimiCodingProvider"] = ((...args) =>
  loadFacadeModule()["buildKimiCodingProvider"](
    ...args,
  )) as FacadeModule["buildKimiCodingProvider"];
