// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["line-runtime"];
type FacadeModule = FacadeEntry["module"];
import {
  createLazyFacadeObjectValue,
  loadBundledPluginPublicSurfaceModuleSync,
} from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "line",
    artifactBasename: "runtime-api.js",
  });
}
export const buildTemplateMessageFromPayload: FacadeModule["buildTemplateMessageFromPayload"] = ((
  ...args
) =>
  loadFacadeModule()["buildTemplateMessageFromPayload"](
    ...args,
  )) as FacadeModule["buildTemplateMessageFromPayload"];
export const cancelDefaultRichMenu: FacadeModule["cancelDefaultRichMenu"] = ((...args) =>
  loadFacadeModule()["cancelDefaultRichMenu"](...args)) as FacadeModule["cancelDefaultRichMenu"];
export const createActionCard: FacadeModule["createActionCard"] = ((...args) =>
  loadFacadeModule()["createActionCard"](...args)) as FacadeModule["createActionCard"];
export const createAgendaCard: FacadeModule["createAgendaCard"] = ((...args) =>
  loadFacadeModule()["createAgendaCard"](...args)) as FacadeModule["createAgendaCard"];
export const createAppleTvRemoteCard: FacadeModule["createAppleTvRemoteCard"] = ((...args) =>
  loadFacadeModule()["createAppleTvRemoteCard"](
    ...args,
  )) as FacadeModule["createAppleTvRemoteCard"];
export const createCarousel: FacadeModule["createCarousel"] = ((...args) =>
  loadFacadeModule()["createCarousel"](...args)) as FacadeModule["createCarousel"];
export const createDefaultMenuConfig: FacadeModule["createDefaultMenuConfig"] = ((...args) =>
  loadFacadeModule()["createDefaultMenuConfig"](
    ...args,
  )) as FacadeModule["createDefaultMenuConfig"];
export const createDeviceControlCard: FacadeModule["createDeviceControlCard"] = ((...args) =>
  loadFacadeModule()["createDeviceControlCard"](
    ...args,
  )) as FacadeModule["createDeviceControlCard"];
export const createEventCard: FacadeModule["createEventCard"] = ((...args) =>
  loadFacadeModule()["createEventCard"](...args)) as FacadeModule["createEventCard"];
export const createGridLayout: FacadeModule["createGridLayout"] = ((...args) =>
  loadFacadeModule()["createGridLayout"](...args)) as FacadeModule["createGridLayout"];
export const createImageCard: FacadeModule["createImageCard"] = ((...args) =>
  loadFacadeModule()["createImageCard"](...args)) as FacadeModule["createImageCard"];
export const createInfoCard: FacadeModule["createInfoCard"] = ((...args) =>
  loadFacadeModule()["createInfoCard"](...args)) as FacadeModule["createInfoCard"];
export const createListCard: FacadeModule["createListCard"] = ((...args) =>
  loadFacadeModule()["createListCard"](...args)) as FacadeModule["createListCard"];
export const createMediaPlayerCard: FacadeModule["createMediaPlayerCard"] = ((...args) =>
  loadFacadeModule()["createMediaPlayerCard"](...args)) as FacadeModule["createMediaPlayerCard"];
export const createNotificationBubble: FacadeModule["createNotificationBubble"] = ((...args) =>
  loadFacadeModule()["createNotificationBubble"](
    ...args,
  )) as FacadeModule["createNotificationBubble"];
export const createQuickReplyItems: FacadeModule["createQuickReplyItems"] = ((...args) =>
  loadFacadeModule()["createQuickReplyItems"](...args)) as FacadeModule["createQuickReplyItems"];
export const createReceiptCard: FacadeModule["createReceiptCard"] = ((...args) =>
  loadFacadeModule()["createReceiptCard"](...args)) as FacadeModule["createReceiptCard"];
export const createRichMenu: FacadeModule["createRichMenu"] = ((...args) =>
  loadFacadeModule()["createRichMenu"](...args)) as FacadeModule["createRichMenu"];
export const createRichMenuAlias: FacadeModule["createRichMenuAlias"] = ((...args) =>
  loadFacadeModule()["createRichMenuAlias"](...args)) as FacadeModule["createRichMenuAlias"];
export const datetimePickerAction: FacadeModule["datetimePickerAction"] = ((...args) =>
  loadFacadeModule()["datetimePickerAction"](...args)) as FacadeModule["datetimePickerAction"];
export const deleteRichMenu: FacadeModule["deleteRichMenu"] = ((...args) =>
  loadFacadeModule()["deleteRichMenu"](...args)) as FacadeModule["deleteRichMenu"];
export const deleteRichMenuAlias: FacadeModule["deleteRichMenuAlias"] = ((...args) =>
  loadFacadeModule()["deleteRichMenuAlias"](...args)) as FacadeModule["deleteRichMenuAlias"];
export const downloadLineMedia: FacadeModule["downloadLineMedia"] = ((...args) =>
  loadFacadeModule()["downloadLineMedia"](...args)) as FacadeModule["downloadLineMedia"];
export const firstDefined: FacadeModule["firstDefined"] = createLazyFacadeObjectValue(
  () => loadFacadeModule()["firstDefined"] as object,
) as FacadeModule["firstDefined"];
export const getDefaultRichMenuId: FacadeModule["getDefaultRichMenuId"] = ((...args) =>
  loadFacadeModule()["getDefaultRichMenuId"](...args)) as FacadeModule["getDefaultRichMenuId"];
export const getRichMenu: FacadeModule["getRichMenu"] = ((...args) =>
  loadFacadeModule()["getRichMenu"](...args)) as FacadeModule["getRichMenu"];
export const getRichMenuIdOfUser: FacadeModule["getRichMenuIdOfUser"] = ((...args) =>
  loadFacadeModule()["getRichMenuIdOfUser"](...args)) as FacadeModule["getRichMenuIdOfUser"];
export const getRichMenuList: FacadeModule["getRichMenuList"] = ((...args) =>
  loadFacadeModule()["getRichMenuList"](...args)) as FacadeModule["getRichMenuList"];
export const isSenderAllowed: FacadeModule["isSenderAllowed"] = ((...args) =>
  loadFacadeModule()["isSenderAllowed"](...args)) as FacadeModule["isSenderAllowed"];
export const linkRichMenuToUser: FacadeModule["linkRichMenuToUser"] = ((...args) =>
  loadFacadeModule()["linkRichMenuToUser"](...args)) as FacadeModule["linkRichMenuToUser"];
export const linkRichMenuToUsers: FacadeModule["linkRichMenuToUsers"] = ((...args) =>
  loadFacadeModule()["linkRichMenuToUsers"](...args)) as FacadeModule["linkRichMenuToUsers"];
export const messageAction: FacadeModule["messageAction"] = ((...args) =>
  loadFacadeModule()["messageAction"](...args)) as FacadeModule["messageAction"];
export const monitorLineProvider: FacadeModule["monitorLineProvider"] = ((...args) =>
  loadFacadeModule()["monitorLineProvider"](...args)) as FacadeModule["monitorLineProvider"];
export const normalizeAllowFrom: FacadeModule["normalizeAllowFrom"] = ((...args) =>
  loadFacadeModule()["normalizeAllowFrom"](...args)) as FacadeModule["normalizeAllowFrom"];
export const normalizeDmAllowFromWithStore: FacadeModule["normalizeDmAllowFromWithStore"] = ((
  ...args
) =>
  loadFacadeModule()["normalizeDmAllowFromWithStore"](
    ...args,
  )) as FacadeModule["normalizeDmAllowFromWithStore"];
export const postbackAction: FacadeModule["postbackAction"] = ((...args) =>
  loadFacadeModule()["postbackAction"](...args)) as FacadeModule["postbackAction"];
export const probeLineBot: FacadeModule["probeLineBot"] = ((...args) =>
  loadFacadeModule()["probeLineBot"](...args)) as FacadeModule["probeLineBot"];
export const pushFlexMessage: FacadeModule["pushFlexMessage"] = ((...args) =>
  loadFacadeModule()["pushFlexMessage"](...args)) as FacadeModule["pushFlexMessage"];
export const pushLocationMessage: FacadeModule["pushLocationMessage"] = ((...args) =>
  loadFacadeModule()["pushLocationMessage"](...args)) as FacadeModule["pushLocationMessage"];
export const pushMessageLine: FacadeModule["pushMessageLine"] = ((...args) =>
  loadFacadeModule()["pushMessageLine"](...args)) as FacadeModule["pushMessageLine"];
export const pushMessagesLine: FacadeModule["pushMessagesLine"] = ((...args) =>
  loadFacadeModule()["pushMessagesLine"](...args)) as FacadeModule["pushMessagesLine"];
export const pushTemplateMessage: FacadeModule["pushTemplateMessage"] = ((...args) =>
  loadFacadeModule()["pushTemplateMessage"](...args)) as FacadeModule["pushTemplateMessage"];
export const pushTextMessageWithQuickReplies: FacadeModule["pushTextMessageWithQuickReplies"] = ((
  ...args
) =>
  loadFacadeModule()["pushTextMessageWithQuickReplies"](
    ...args,
  )) as FacadeModule["pushTextMessageWithQuickReplies"];
export const sendMessageLine: FacadeModule["sendMessageLine"] = ((...args) =>
  loadFacadeModule()["sendMessageLine"](...args)) as FacadeModule["sendMessageLine"];
export const setDefaultRichMenu: FacadeModule["setDefaultRichMenu"] = ((...args) =>
  loadFacadeModule()["setDefaultRichMenu"](...args)) as FacadeModule["setDefaultRichMenu"];
export const toFlexMessage: FacadeModule["toFlexMessage"] = ((...args) =>
  loadFacadeModule()["toFlexMessage"](...args)) as FacadeModule["toFlexMessage"];
export const unlinkRichMenuFromUser: FacadeModule["unlinkRichMenuFromUser"] = ((...args) =>
  loadFacadeModule()["unlinkRichMenuFromUser"](...args)) as FacadeModule["unlinkRichMenuFromUser"];
export const unlinkRichMenuFromUsers: FacadeModule["unlinkRichMenuFromUsers"] = ((...args) =>
  loadFacadeModule()["unlinkRichMenuFromUsers"](
    ...args,
  )) as FacadeModule["unlinkRichMenuFromUsers"];
export const uploadRichMenuImage: FacadeModule["uploadRichMenuImage"] = ((...args) =>
  loadFacadeModule()["uploadRichMenuImage"](...args)) as FacadeModule["uploadRichMenuImage"];
export const uriAction: FacadeModule["uriAction"] = ((...args) =>
  loadFacadeModule()["uriAction"](...args)) as FacadeModule["uriAction"];
export type Action = FacadeEntry["types"]["Action"];
export type CardAction = FacadeEntry["types"]["CardAction"];
export type CreateRichMenuParams = FacadeEntry["types"]["CreateRichMenuParams"];
export type FlexBox = FacadeEntry["types"]["FlexBox"];
export type FlexBubble = FacadeEntry["types"]["FlexBubble"];
export type FlexButton = FacadeEntry["types"]["FlexButton"];
export type FlexCarousel = FacadeEntry["types"]["FlexCarousel"];
export type FlexComponent = FacadeEntry["types"]["FlexComponent"];
export type FlexContainer = FacadeEntry["types"]["FlexContainer"];
export type FlexImage = FacadeEntry["types"]["FlexImage"];
export type FlexText = FacadeEntry["types"]["FlexText"];
export type LineChannelData = FacadeEntry["types"]["LineChannelData"];
export type LineConfig = FacadeEntry["types"]["LineConfig"];
export type LineProbeResult = FacadeEntry["types"]["LineProbeResult"];
export type ListItem = FacadeEntry["types"]["ListItem"];
export type ResolvedLineAccount = FacadeEntry["types"]["ResolvedLineAccount"];
export type RichMenuArea = FacadeEntry["types"]["RichMenuArea"];
export type RichMenuAreaRequest = FacadeEntry["types"]["RichMenuAreaRequest"];
export type RichMenuRequest = FacadeEntry["types"]["RichMenuRequest"];
export type RichMenuResponse = FacadeEntry["types"]["RichMenuResponse"];
export type RichMenuSize = FacadeEntry["types"]["RichMenuSize"];
