// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  setMatrixThreadBindingIdleTimeoutBySessionKey,
  setMatrixThreadBindingMaxAgeBySessionKey,
} from "../../extensions/matrix/api.js";
