// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  findMatrixAccountEntry,
  getMatrixScopedEnvVarNames,
  requiresExplicitMatrixDefaultAccount,
  resolveConfiguredMatrixAccountIds,
  resolveMatrixAccountStorageRoot,
  resolveMatrixChannelConfig,
  resolveMatrixCredentialsDir,
  resolveMatrixCredentialsPath,
  resolveMatrixDefaultOrOnlyAccountId,
  resolveMatrixLegacyFlatStoragePaths,
} from "../../extensions/matrix/api.js";
