// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["media-understanding-runtime"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "media-understanding-core",
    artifactBasename: "runtime-api.js",
  });
}
export const describeImageFile: FacadeModule["describeImageFile"] = ((...args) =>
  loadFacadeModule()["describeImageFile"](...args)) as FacadeModule["describeImageFile"];
export const describeImageFileWithModel: FacadeModule["describeImageFileWithModel"] = ((...args) =>
  loadFacadeModule()["describeImageFileWithModel"](
    ...args,
  )) as FacadeModule["describeImageFileWithModel"];
export const describeVideoFile: FacadeModule["describeVideoFile"] = ((...args) =>
  loadFacadeModule()["describeVideoFile"](...args)) as FacadeModule["describeVideoFile"];
export const runMediaUnderstandingFile: FacadeModule["runMediaUnderstandingFile"] = ((...args) =>
  loadFacadeModule()["runMediaUnderstandingFile"](
    ...args,
  )) as FacadeModule["runMediaUnderstandingFile"];
export const transcribeAudioFile: FacadeModule["transcribeAudioFile"] = ((...args) =>
  loadFacadeModule()["transcribeAudioFile"](...args)) as FacadeModule["transcribeAudioFile"];
export type RunMediaUnderstandingFileParams =
  FacadeEntry["types"]["RunMediaUnderstandingFileParams"];
export type RunMediaUnderstandingFileResult =
  FacadeEntry["types"]["RunMediaUnderstandingFileResult"];
