// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["minimax"];
type FacadeModule = FacadeEntry["module"];
import {
  createLazyFacadeObjectValue,
  createLazyFacadeArrayValue,
  loadBundledPluginPublicSurfaceModuleSync,
} from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "minimax",
    artifactBasename: "api.js",
  });
}
export const applyMinimaxApiConfig: FacadeModule["applyMinimaxApiConfig"] = ((...args) =>
  loadFacadeModule()["applyMinimaxApiConfig"](...args)) as FacadeModule["applyMinimaxApiConfig"];
export const applyMinimaxApiConfigCn: FacadeModule["applyMinimaxApiConfigCn"] = ((...args) =>
  loadFacadeModule()["applyMinimaxApiConfigCn"](
    ...args,
  )) as FacadeModule["applyMinimaxApiConfigCn"];
export const applyMinimaxApiProviderConfig: FacadeModule["applyMinimaxApiProviderConfig"] = ((
  ...args
) =>
  loadFacadeModule()["applyMinimaxApiProviderConfig"](
    ...args,
  )) as FacadeModule["applyMinimaxApiProviderConfig"];
export const applyMinimaxApiProviderConfigCn: FacadeModule["applyMinimaxApiProviderConfigCn"] = ((
  ...args
) =>
  loadFacadeModule()["applyMinimaxApiProviderConfigCn"](
    ...args,
  )) as FacadeModule["applyMinimaxApiProviderConfigCn"];
export const buildMinimaxPortalProvider: FacadeModule["buildMinimaxPortalProvider"] = ((...args) =>
  loadFacadeModule()["buildMinimaxPortalProvider"](
    ...args,
  )) as FacadeModule["buildMinimaxPortalProvider"];
export const buildMinimaxProvider: FacadeModule["buildMinimaxProvider"] = ((...args) =>
  loadFacadeModule()["buildMinimaxProvider"](...args)) as FacadeModule["buildMinimaxProvider"];
export const isMiniMaxModernModelId: FacadeModule["isMiniMaxModernModelId"] = ((...args) =>
  loadFacadeModule()["isMiniMaxModernModelId"](...args)) as FacadeModule["isMiniMaxModernModelId"];
export const MINIMAX_API_BASE_URL: FacadeModule["MINIMAX_API_BASE_URL"] =
  loadFacadeModule()["MINIMAX_API_BASE_URL"];
export const MINIMAX_CN_API_BASE_URL: FacadeModule["MINIMAX_CN_API_BASE_URL"] =
  loadFacadeModule()["MINIMAX_CN_API_BASE_URL"];
export const MINIMAX_DEFAULT_MODEL_ID: FacadeModule["MINIMAX_DEFAULT_MODEL_ID"] =
  loadFacadeModule()["MINIMAX_DEFAULT_MODEL_ID"];
export const MINIMAX_DEFAULT_MODEL_REF: FacadeModule["MINIMAX_DEFAULT_MODEL_REF"] =
  loadFacadeModule()["MINIMAX_DEFAULT_MODEL_REF"];
export const MINIMAX_TEXT_MODEL_CATALOG: FacadeModule["MINIMAX_TEXT_MODEL_CATALOG"] =
  createLazyFacadeObjectValue(
    () => loadFacadeModule()["MINIMAX_TEXT_MODEL_CATALOG"] as object,
  ) as FacadeModule["MINIMAX_TEXT_MODEL_CATALOG"];
export const MINIMAX_TEXT_MODEL_ORDER: FacadeModule["MINIMAX_TEXT_MODEL_ORDER"] =
  createLazyFacadeArrayValue(
    () => loadFacadeModule()["MINIMAX_TEXT_MODEL_ORDER"] as unknown as readonly unknown[],
  ) as FacadeModule["MINIMAX_TEXT_MODEL_ORDER"];
export const MINIMAX_TEXT_MODEL_REFS: FacadeModule["MINIMAX_TEXT_MODEL_REFS"] =
  createLazyFacadeArrayValue(
    () => loadFacadeModule()["MINIMAX_TEXT_MODEL_REFS"] as unknown as readonly unknown[],
  ) as FacadeModule["MINIMAX_TEXT_MODEL_REFS"];
