// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["mistral"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "mistral",
    artifactBasename: "api.js",
  });
}
export const applyMistralConfig: FacadeModule["applyMistralConfig"] = ((...args) =>
  loadFacadeModule()["applyMistralConfig"](...args)) as FacadeModule["applyMistralConfig"];
export const applyMistralProviderConfig: FacadeModule["applyMistralProviderConfig"] = ((...args) =>
  loadFacadeModule()["applyMistralProviderConfig"](
    ...args,
  )) as FacadeModule["applyMistralProviderConfig"];
export const buildMistralModelDefinition: FacadeModule["buildMistralModelDefinition"] = ((
  ...args
) =>
  loadFacadeModule()["buildMistralModelDefinition"](
    ...args,
  )) as FacadeModule["buildMistralModelDefinition"];
export const buildMistralProvider: FacadeModule["buildMistralProvider"] = ((...args) =>
  loadFacadeModule()["buildMistralProvider"](...args)) as FacadeModule["buildMistralProvider"];
export const MISTRAL_BASE_URL: FacadeModule["MISTRAL_BASE_URL"] =
  loadFacadeModule()["MISTRAL_BASE_URL"];
export const MISTRAL_DEFAULT_MODEL_ID: FacadeModule["MISTRAL_DEFAULT_MODEL_ID"] =
  loadFacadeModule()["MISTRAL_DEFAULT_MODEL_ID"];
export const MISTRAL_DEFAULT_MODEL_REF: FacadeModule["MISTRAL_DEFAULT_MODEL_REF"] =
  loadFacadeModule()["MISTRAL_DEFAULT_MODEL_REF"];
