// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  applyModelStudioNativeStreamingUsageCompat,
  buildModelStudioDefaultModelDefinition,
  buildModelStudioModelDefinition,
  MODELSTUDIO_BASE_URL,
  MODELSTUDIO_CN_BASE_URL,
  MODELSTUDIO_DEFAULT_COST,
  MODELSTUDIO_DEFAULT_MODEL_ID,
  MODELSTUDIO_DEFAULT_MODEL_REF,
  MODELSTUDIO_GLOBAL_BASE_URL,
  MODELSTUDIO_STANDARD_CN_BASE_URL,
  MODELSTUDIO_STANDARD_GLOBAL_BASE_URL,
  MODELSTUDIO_MODEL_CATALOG,
  isNativeModelStudioBaseUrl,
  buildModelStudioProvider,
} from "../../extensions/modelstudio/api.js";
