// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["modelstudio-definitions"];
type FacadeModule = FacadeEntry["module"];
import {
  createLazyFacadeObjectValue,
  loadBundledPluginPublicSurfaceModuleSync,
} from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "modelstudio",
    artifactBasename: "api.js",
  });
}
export const buildModelStudioDefaultModelDefinition: FacadeModule["buildModelStudioDefaultModelDefinition"] =
  ((...args) =>
    loadFacadeModule()["buildModelStudioDefaultModelDefinition"](
      ...args,
    )) as FacadeModule["buildModelStudioDefaultModelDefinition"];
export const buildModelStudioModelDefinition: FacadeModule["buildModelStudioModelDefinition"] = ((
  ...args
) =>
  loadFacadeModule()["buildModelStudioModelDefinition"](
    ...args,
  )) as FacadeModule["buildModelStudioModelDefinition"];
export const MODELSTUDIO_CN_BASE_URL: FacadeModule["MODELSTUDIO_CN_BASE_URL"] =
  loadFacadeModule()["MODELSTUDIO_CN_BASE_URL"];
export const MODELSTUDIO_DEFAULT_COST: FacadeModule["MODELSTUDIO_DEFAULT_COST"] =
  createLazyFacadeObjectValue(
    () => loadFacadeModule()["MODELSTUDIO_DEFAULT_COST"] as object,
  ) as FacadeModule["MODELSTUDIO_DEFAULT_COST"];
export const MODELSTUDIO_DEFAULT_MODEL_ID: FacadeModule["MODELSTUDIO_DEFAULT_MODEL_ID"] =
  loadFacadeModule()["MODELSTUDIO_DEFAULT_MODEL_ID"];
export const MODELSTUDIO_DEFAULT_MODEL_REF: FacadeModule["MODELSTUDIO_DEFAULT_MODEL_REF"] =
  loadFacadeModule()["MODELSTUDIO_DEFAULT_MODEL_REF"];
export const MODELSTUDIO_GLOBAL_BASE_URL: FacadeModule["MODELSTUDIO_GLOBAL_BASE_URL"] =
  loadFacadeModule()["MODELSTUDIO_GLOBAL_BASE_URL"];
export const MODELSTUDIO_STANDARD_CN_BASE_URL: FacadeModule["MODELSTUDIO_STANDARD_CN_BASE_URL"] =
  loadFacadeModule()["MODELSTUDIO_STANDARD_CN_BASE_URL"];
export const MODELSTUDIO_STANDARD_GLOBAL_BASE_URL: FacadeModule["MODELSTUDIO_STANDARD_GLOBAL_BASE_URL"] =
  loadFacadeModule()["MODELSTUDIO_STANDARD_GLOBAL_BASE_URL"];
