// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  applyMoonshotNativeStreamingUsageCompat,
  buildMoonshotProvider,
  isNativeMoonshotBaseUrl,
  MOONSHOT_BASE_URL,
  MOONSHOT_CN_BASE_URL,
  MOONSHOT_DEFAULT_MODEL_ID,
  MOONSHOT_DEFAULT_MODEL_REF,
} from "../../extensions/moonshot/api.js";
