// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["nvidia"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "nvidia",
    artifactBasename: "api.js",
  });
}
export const buildNvidiaProvider: FacadeModule["buildNvidiaProvider"] = ((...args) =>
  loadFacadeModule()["buildNvidiaProvider"](...args)) as FacadeModule["buildNvidiaProvider"];
