// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  buildOllamaModelDefinition,
  buildOllamaProvider,
  configureOllamaNonInteractive,
  ensureOllamaModelPulled,
  enrichOllamaModelsWithContext,
  fetchOllamaModels,
  OLLAMA_DEFAULT_BASE_URL,
  OLLAMA_DEFAULT_CONTEXT_WINDOW,
  OLLAMA_DEFAULT_COST,
  OLLAMA_DEFAULT_MAX_TOKENS,
  OLLAMA_DEFAULT_MODEL,
  promptAndConfigureOllama,
  queryOllamaContextWindow,
  resolveOllamaApiBase,
} from "../../extensions/ollama/api.js";
export type {
  OllamaModelWithContext,
  OllamaTagModel,
  OllamaTagsResponse,
} from "../../extensions/ollama/api.js";
