// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["opencode-go"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "opencode-go",
    artifactBasename: "api.js",
  });
}
export const applyOpencodeGoConfig: FacadeModule["applyOpencodeGoConfig"] = ((...args) =>
  loadFacadeModule()["applyOpencodeGoConfig"](...args)) as FacadeModule["applyOpencodeGoConfig"];
export const applyOpencodeGoModelDefault: FacadeModule["applyOpencodeGoModelDefault"] = ((
  ...args
) =>
  loadFacadeModule()["applyOpencodeGoModelDefault"](
    ...args,
  )) as FacadeModule["applyOpencodeGoModelDefault"];
export const applyOpencodeGoProviderConfig: FacadeModule["applyOpencodeGoProviderConfig"] = ((
  ...args
) =>
  loadFacadeModule()["applyOpencodeGoProviderConfig"](
    ...args,
  )) as FacadeModule["applyOpencodeGoProviderConfig"];
export const OPENCODE_GO_DEFAULT_MODEL_REF: FacadeModule["OPENCODE_GO_DEFAULT_MODEL_REF"] =
  loadFacadeModule()["OPENCODE_GO_DEFAULT_MODEL_REF"];
