// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  applyOpencodeZenConfig,
  applyOpencodeZenModelDefault,
  applyOpencodeZenProviderConfig,
  OPENCODE_ZEN_DEFAULT_MODEL,
  OPENCODE_ZEN_DEFAULT_MODEL_REF,
} from "../../extensions/opencode/api.js";
