// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  applyOpencodeGoConfig,
  applyOpencodeGoModelDefault,
  applyOpencodeGoProviderConfig,
  OPENCODE_GO_DEFAULT_MODEL_REF,
} from "../../extensions/opencode-go/api.js";
