// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["openai"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "openai",
    artifactBasename: "api.js",
  });
}
export const applyOpenAIConfig: FacadeModule["applyOpenAIConfig"] = ((...args) =>
  loadFacadeModule()["applyOpenAIConfig"](...args)) as FacadeModule["applyOpenAIConfig"];
export const applyOpenAIProviderConfig: FacadeModule["applyOpenAIProviderConfig"] = ((...args) =>
  loadFacadeModule()["applyOpenAIProviderConfig"](
    ...args,
  )) as FacadeModule["applyOpenAIProviderConfig"];
export const buildOpenAICodexProvider: FacadeModule["buildOpenAICodexProvider"] = ((...args) =>
  loadFacadeModule()["buildOpenAICodexProvider"](
    ...args,
  )) as FacadeModule["buildOpenAICodexProvider"];
export const buildOpenAIProvider: FacadeModule["buildOpenAIProvider"] = ((...args) =>
  loadFacadeModule()["buildOpenAIProvider"](...args)) as FacadeModule["buildOpenAIProvider"];
export const OPENAI_CODEX_DEFAULT_MODEL: FacadeModule["OPENAI_CODEX_DEFAULT_MODEL"] =
  loadFacadeModule()["OPENAI_CODEX_DEFAULT_MODEL"];
export const OPENAI_DEFAULT_AUDIO_TRANSCRIPTION_MODEL: FacadeModule["OPENAI_DEFAULT_AUDIO_TRANSCRIPTION_MODEL"] =
  loadFacadeModule()["OPENAI_DEFAULT_AUDIO_TRANSCRIPTION_MODEL"];
export const OPENAI_DEFAULT_EMBEDDING_MODEL: FacadeModule["OPENAI_DEFAULT_EMBEDDING_MODEL"] =
  loadFacadeModule()["OPENAI_DEFAULT_EMBEDDING_MODEL"];
export const OPENAI_DEFAULT_IMAGE_MODEL: FacadeModule["OPENAI_DEFAULT_IMAGE_MODEL"] =
  loadFacadeModule()["OPENAI_DEFAULT_IMAGE_MODEL"];
export const OPENAI_DEFAULT_MODEL: FacadeModule["OPENAI_DEFAULT_MODEL"] =
  loadFacadeModule()["OPENAI_DEFAULT_MODEL"];
export const OPENAI_DEFAULT_TTS_MODEL: FacadeModule["OPENAI_DEFAULT_TTS_MODEL"] =
  loadFacadeModule()["OPENAI_DEFAULT_TTS_MODEL"];
export const OPENAI_DEFAULT_TTS_VOICE: FacadeModule["OPENAI_DEFAULT_TTS_VOICE"] =
  loadFacadeModule()["OPENAI_DEFAULT_TTS_VOICE"];
