// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["opencode"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "opencode",
    artifactBasename: "api.js",
  });
}
export const applyOpencodeZenConfig: FacadeModule["applyOpencodeZenConfig"] = ((...args) =>
  loadFacadeModule()["applyOpencodeZenConfig"](...args)) as FacadeModule["applyOpencodeZenConfig"];
export const applyOpencodeZenModelDefault: FacadeModule["applyOpencodeZenModelDefault"] = ((
  ...args
) =>
  loadFacadeModule()["applyOpencodeZenModelDefault"](
    ...args,
  )) as FacadeModule["applyOpencodeZenModelDefault"];
export const applyOpencodeZenProviderConfig: FacadeModule["applyOpencodeZenProviderConfig"] = ((
  ...args
) =>
  loadFacadeModule()["applyOpencodeZenProviderConfig"](
    ...args,
  )) as FacadeModule["applyOpencodeZenProviderConfig"];
export const OPENCODE_ZEN_DEFAULT_MODEL: FacadeModule["OPENCODE_ZEN_DEFAULT_MODEL"] =
  loadFacadeModule()["OPENCODE_ZEN_DEFAULT_MODEL"];
export const OPENCODE_ZEN_DEFAULT_MODEL_REF: FacadeModule["OPENCODE_ZEN_DEFAULT_MODEL_REF"] =
  loadFacadeModule()["OPENCODE_ZEN_DEFAULT_MODEL_REF"];
