// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["provider-reasoning"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "ollama",
    artifactBasename: "api.js",
  });
}
export const isReasoningModelHeuristic: FacadeModule["isReasoningModelHeuristic"] = ((...args) =>
  loadFacadeModule()["isReasoningModelHeuristic"](
    ...args,
  )) as FacadeModule["isReasoningModelHeuristic"];
