// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["qianfan"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "qianfan",
    artifactBasename: "api.js",
  });
}
export const QIANFAN_BASE_URL: FacadeModule["QIANFAN_BASE_URL"] =
  loadFacadeModule()["QIANFAN_BASE_URL"];
export const QIANFAN_DEFAULT_MODEL_ID: FacadeModule["QIANFAN_DEFAULT_MODEL_ID"] =
  loadFacadeModule()["QIANFAN_DEFAULT_MODEL_ID"];
export const buildQianfanProvider: FacadeModule["buildQianfanProvider"] = ((...args) =>
  loadFacadeModule()["buildQianfanProvider"](...args)) as FacadeModule["buildQianfanProvider"];
