// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  QIANFAN_BASE_URL,
  QIANFAN_DEFAULT_MODEL_ID,
  buildQianfanProvider,
} from "../../extensions/qianfan/api.js";
