// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["sglang"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "sglang",
    artifactBasename: "api.js",
  });
}
export const buildSglangProvider: FacadeModule["buildSglangProvider"] = ((...args) =>
  loadFacadeModule()["buildSglangProvider"](...args)) as FacadeModule["buildSglangProvider"];
export const SGLANG_DEFAULT_API_KEY_ENV_VAR: FacadeModule["SGLANG_DEFAULT_API_KEY_ENV_VAR"] =
  loadFacadeModule()["SGLANG_DEFAULT_API_KEY_ENV_VAR"];
export const SGLANG_DEFAULT_BASE_URL: FacadeModule["SGLANG_DEFAULT_BASE_URL"] =
  loadFacadeModule()["SGLANG_DEFAULT_BASE_URL"];
export const SGLANG_MODEL_PLACEHOLDER: FacadeModule["SGLANG_MODEL_PLACEHOLDER"] =
  loadFacadeModule()["SGLANG_MODEL_PLACEHOLDER"];
export const SGLANG_PROVIDER_LABEL: FacadeModule["SGLANG_PROVIDER_LABEL"] =
  loadFacadeModule()["SGLANG_PROVIDER_LABEL"];
