// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["signal-account"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "signal",
    artifactBasename: "api.js",
  });
}
export const resolveSignalAccount: FacadeModule["resolveSignalAccount"] = ((...args) =>
  loadFacadeModule()["resolveSignalAccount"](...args)) as FacadeModule["resolveSignalAccount"];
export type ResolvedSignalAccount = FacadeEntry["types"]["ResolvedSignalAccount"];
