// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["slack-account"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "slack",
    artifactBasename: "api.js",
  });
}
export const resolveSlackAccount: FacadeModule["resolveSlackAccount"] = ((...args) =>
  loadFacadeModule()["resolveSlackAccount"](...args)) as FacadeModule["resolveSlackAccount"];
export type ResolvedSlackAccount = FacadeEntry["types"]["ResolvedSlackAccount"];
