// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["slack-target-parser"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "slack",
    artifactBasename: "api.js",
  });
}
export const parseSlackTarget: FacadeModule["parseSlackTarget"] = ((...args) =>
  loadFacadeModule()["parseSlackTarget"](...args)) as FacadeModule["parseSlackTarget"];
export const resolveSlackChannelId: FacadeModule["resolveSlackChannelId"] = ((...args) =>
  loadFacadeModule()["resolveSlackChannelId"](...args)) as FacadeModule["resolveSlackChannelId"];
