// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export { resolveSlackAccount } from "../../extensions/slack/api.js";
export type { ResolvedSlackAccount } from "../../extensions/slack/api.js";
