// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["synthetic"];
type FacadeModule = FacadeEntry["module"];
import {
  createLazyFacadeArrayValue,
  loadBundledPluginPublicSurfaceModuleSync,
} from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "synthetic",
    artifactBasename: "api.js",
  });
}
export const applySyntheticConfig: FacadeModule["applySyntheticConfig"] = ((...args) =>
  loadFacadeModule()["applySyntheticConfig"](...args)) as FacadeModule["applySyntheticConfig"];
export const applySyntheticProviderConfig: FacadeModule["applySyntheticProviderConfig"] = ((
  ...args
) =>
  loadFacadeModule()["applySyntheticProviderConfig"](
    ...args,
  )) as FacadeModule["applySyntheticProviderConfig"];
export const buildSyntheticModelDefinition: FacadeModule["buildSyntheticModelDefinition"] = ((
  ...args
) =>
  loadFacadeModule()["buildSyntheticModelDefinition"](
    ...args,
  )) as FacadeModule["buildSyntheticModelDefinition"];
export const buildSyntheticProvider: FacadeModule["buildSyntheticProvider"] = ((...args) =>
  loadFacadeModule()["buildSyntheticProvider"](...args)) as FacadeModule["buildSyntheticProvider"];
export const SYNTHETIC_BASE_URL: FacadeModule["SYNTHETIC_BASE_URL"] =
  loadFacadeModule()["SYNTHETIC_BASE_URL"];
export const SYNTHETIC_DEFAULT_MODEL_ID: FacadeModule["SYNTHETIC_DEFAULT_MODEL_ID"] =
  loadFacadeModule()["SYNTHETIC_DEFAULT_MODEL_ID"];
export const SYNTHETIC_DEFAULT_MODEL_REF: FacadeModule["SYNTHETIC_DEFAULT_MODEL_REF"] =
  loadFacadeModule()["SYNTHETIC_DEFAULT_MODEL_REF"];
export const SYNTHETIC_MODEL_CATALOG: FacadeModule["SYNTHETIC_MODEL_CATALOG"] =
  createLazyFacadeArrayValue(
    () => loadFacadeModule()["SYNTHETIC_MODEL_CATALOG"] as unknown as readonly unknown[],
  ) as FacadeModule["SYNTHETIC_MODEL_CATALOG"];
