// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  buildSyntheticModelDefinition,
  buildSyntheticProvider,
  SYNTHETIC_BASE_URL,
  SYNTHETIC_DEFAULT_MODEL_REF,
  SYNTHETIC_MODEL_CATALOG,
} from "../../extensions/synthetic/api.js";
