// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export { resolveTelegramAccount } from "../../extensions/telegram/api.js";
export type { ResolvedTelegramAccount } from "../../extensions/telegram/api.js";
