// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["telegram-account"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "telegram",
    artifactBasename: "api.js",
  });
}
export const resolveTelegramAccount: FacadeModule["resolveTelegramAccount"] = ((...args) =>
  loadFacadeModule()["resolveTelegramAccount"](...args)) as FacadeModule["resolveTelegramAccount"];
export type ResolvedTelegramAccount = FacadeEntry["types"]["ResolvedTelegramAccount"];
