// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["telegram-allow-from"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "telegram",
    artifactBasename: "api.js",
  });
}
export const isNumericTelegramUserId: FacadeModule["isNumericTelegramUserId"] = ((...args) =>
  loadFacadeModule()["isNumericTelegramUserId"](
    ...args,
  )) as FacadeModule["isNumericTelegramUserId"];
export const normalizeTelegramAllowFromEntry: FacadeModule["normalizeTelegramAllowFromEntry"] = ((
  ...args
) =>
  loadFacadeModule()["normalizeTelegramAllowFromEntry"](
    ...args,
  )) as FacadeModule["normalizeTelegramAllowFromEntry"];
