// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["together"];
type FacadeModule = FacadeEntry["module"];
import {
  createLazyFacadeArrayValue,
  loadBundledPluginPublicSurfaceModuleSync,
} from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "together",
    artifactBasename: "api.js",
  });
}
export const applyTogetherConfig: FacadeModule["applyTogetherConfig"] = ((...args) =>
  loadFacadeModule()["applyTogetherConfig"](...args)) as FacadeModule["applyTogetherConfig"];
export const buildTogetherModelDefinition: FacadeModule["buildTogetherModelDefinition"] = ((
  ...args
) =>
  loadFacadeModule()["buildTogetherModelDefinition"](
    ...args,
  )) as FacadeModule["buildTogetherModelDefinition"];
export const buildTogetherProvider: FacadeModule["buildTogetherProvider"] = ((...args) =>
  loadFacadeModule()["buildTogetherProvider"](...args)) as FacadeModule["buildTogetherProvider"];
export const TOGETHER_BASE_URL: FacadeModule["TOGETHER_BASE_URL"] =
  loadFacadeModule()["TOGETHER_BASE_URL"];
export const TOGETHER_DEFAULT_MODEL_REF: FacadeModule["TOGETHER_DEFAULT_MODEL_REF"] =
  loadFacadeModule()["TOGETHER_DEFAULT_MODEL_REF"];
export const TOGETHER_MODEL_CATALOG: FacadeModule["TOGETHER_MODEL_CATALOG"] =
  createLazyFacadeArrayValue(
    () => loadFacadeModule()["TOGETHER_MODEL_CATALOG"] as unknown as readonly unknown[],
  ) as FacadeModule["TOGETHER_MODEL_CATALOG"];
