// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["venice"];
type FacadeModule = FacadeEntry["module"];
import {
  createLazyFacadeArrayValue,
  loadBundledPluginPublicSurfaceModuleSync,
} from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "venice",
    artifactBasename: "api.js",
  });
}
export const buildVeniceModelDefinition: FacadeModule["buildVeniceModelDefinition"] = ((...args) =>
  loadFacadeModule()["buildVeniceModelDefinition"](
    ...args,
  )) as FacadeModule["buildVeniceModelDefinition"];
export const buildVeniceProvider: FacadeModule["buildVeniceProvider"] = ((...args) =>
  loadFacadeModule()["buildVeniceProvider"](...args)) as FacadeModule["buildVeniceProvider"];
export const discoverVeniceModels: FacadeModule["discoverVeniceModels"] = ((...args) =>
  loadFacadeModule()["discoverVeniceModels"](...args)) as FacadeModule["discoverVeniceModels"];
export const VENICE_BASE_URL: FacadeModule["VENICE_BASE_URL"] =
  loadFacadeModule()["VENICE_BASE_URL"];
export const VENICE_DEFAULT_MODEL_REF: FacadeModule["VENICE_DEFAULT_MODEL_REF"] =
  loadFacadeModule()["VENICE_DEFAULT_MODEL_REF"];
export const VENICE_MODEL_CATALOG: FacadeModule["VENICE_MODEL_CATALOG"] =
  createLazyFacadeArrayValue(
    () => loadFacadeModule()["VENICE_MODEL_CATALOG"] as unknown as readonly unknown[],
  ) as FacadeModule["VENICE_MODEL_CATALOG"];
