// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  buildVercelAiGatewayProvider,
  discoverVercelAiGatewayModels,
  getStaticVercelAiGatewayModelCatalog,
  VERCEL_AI_GATEWAY_BASE_URL,
  VERCEL_AI_GATEWAY_DEFAULT_CONTEXT_WINDOW,
  VERCEL_AI_GATEWAY_DEFAULT_COST,
  VERCEL_AI_GATEWAY_DEFAULT_MAX_TOKENS,
  VERCEL_AI_GATEWAY_DEFAULT_MODEL_ID,
  VERCEL_AI_GATEWAY_DEFAULT_MODEL_REF,
  VERCEL_AI_GATEWAY_PROVIDER_ID,
} from "../../extensions/vercel-ai-gateway/api.js";
