// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  buildVllmProvider,
  VLLM_DEFAULT_API_KEY_ENV_VAR,
  VLLM_DEFAULT_BASE_URL,
  VLLM_MODEL_PLACEHOLDER,
  VLLM_PROVIDER_LABEL,
} from "../../extensions/vllm/api.js";
