// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["vllm"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "vllm",
    artifactBasename: "api.js",
  });
}
export const buildVllmProvider: FacadeModule["buildVllmProvider"] = ((...args) =>
  loadFacadeModule()["buildVllmProvider"](...args)) as FacadeModule["buildVllmProvider"];
export const VLLM_DEFAULT_API_KEY_ENV_VAR: FacadeModule["VLLM_DEFAULT_API_KEY_ENV_VAR"] =
  loadFacadeModule()["VLLM_DEFAULT_API_KEY_ENV_VAR"];
export const VLLM_DEFAULT_BASE_URL: FacadeModule["VLLM_DEFAULT_BASE_URL"] =
  loadFacadeModule()["VLLM_DEFAULT_BASE_URL"];
export const VLLM_MODEL_PLACEHOLDER: FacadeModule["VLLM_MODEL_PLACEHOLDER"] =
  loadFacadeModule()["VLLM_MODEL_PLACEHOLDER"];
export const VLLM_PROVIDER_LABEL: FacadeModule["VLLM_PROVIDER_LABEL"] =
  loadFacadeModule()["VLLM_PROVIDER_LABEL"];
