// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["volcengine"];
type FacadeModule = FacadeEntry["module"];
import {
  createLazyFacadeArrayValue,
  loadBundledPluginPublicSurfaceModuleSync,
} from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "volcengine",
    artifactBasename: "api.js",
  });
}
export const buildDoubaoCodingProvider: FacadeModule["buildDoubaoCodingProvider"] = ((...args) =>
  loadFacadeModule()["buildDoubaoCodingProvider"](
    ...args,
  )) as FacadeModule["buildDoubaoCodingProvider"];
export const buildDoubaoModelDefinition: FacadeModule["buildDoubaoModelDefinition"] = ((...args) =>
  loadFacadeModule()["buildDoubaoModelDefinition"](
    ...args,
  )) as FacadeModule["buildDoubaoModelDefinition"];
export const buildDoubaoProvider: FacadeModule["buildDoubaoProvider"] = ((...args) =>
  loadFacadeModule()["buildDoubaoProvider"](...args)) as FacadeModule["buildDoubaoProvider"];
export const DOUBAO_BASE_URL: FacadeModule["DOUBAO_BASE_URL"] =
  loadFacadeModule()["DOUBAO_BASE_URL"];
export const DOUBAO_CODING_BASE_URL: FacadeModule["DOUBAO_CODING_BASE_URL"] =
  loadFacadeModule()["DOUBAO_CODING_BASE_URL"];
export const DOUBAO_CODING_MODEL_CATALOG: FacadeModule["DOUBAO_CODING_MODEL_CATALOG"] =
  createLazyFacadeArrayValue(
    () => loadFacadeModule()["DOUBAO_CODING_MODEL_CATALOG"] as unknown as readonly unknown[],
  ) as FacadeModule["DOUBAO_CODING_MODEL_CATALOG"];
export const DOUBAO_MODEL_CATALOG: FacadeModule["DOUBAO_MODEL_CATALOG"] =
  createLazyFacadeArrayValue(
    () => loadFacadeModule()["DOUBAO_MODEL_CATALOG"] as unknown as readonly unknown[],
  ) as FacadeModule["DOUBAO_MODEL_CATALOG"];
