// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  isWhatsAppGroupJid,
  isWhatsAppUserTarget,
  normalizeWhatsAppTarget,
} from "../../extensions/whatsapp/api.js";
