// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["whatsapp-surface"];
type FacadeModule = FacadeEntry["module"];
type FacadeModule2 = FacadeEntry["sourceModules"]["source2"]["module"];
import {
  createLazyFacadeObjectValue,
  loadBundledPluginPublicSurfaceModuleSync,
} from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "whatsapp",
    artifactBasename: "api.js",
  });
}

function loadFacadeModule2(): FacadeModule2 {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule2>({
    dirName: "whatsapp",
    artifactBasename: "constants.js",
  });
}
export const DEFAULT_WEB_MEDIA_BYTES: FacadeModule2["DEFAULT_WEB_MEDIA_BYTES"] =
  loadFacadeModule2()["DEFAULT_WEB_MEDIA_BYTES"];
export const hasAnyWhatsAppAuth: FacadeModule["hasAnyWhatsAppAuth"] = ((...args) =>
  loadFacadeModule()["hasAnyWhatsAppAuth"](...args)) as FacadeModule["hasAnyWhatsAppAuth"];
export const listEnabledWhatsAppAccounts: FacadeModule["listEnabledWhatsAppAccounts"] = ((
  ...args
) =>
  loadFacadeModule()["listEnabledWhatsAppAccounts"](
    ...args,
  )) as FacadeModule["listEnabledWhatsAppAccounts"];
export const listWhatsAppDirectoryGroupsFromConfig: FacadeModule["listWhatsAppDirectoryGroupsFromConfig"] =
  ((...args) =>
    loadFacadeModule()["listWhatsAppDirectoryGroupsFromConfig"](
      ...args,
    )) as FacadeModule["listWhatsAppDirectoryGroupsFromConfig"];
export const listWhatsAppDirectoryPeersFromConfig: FacadeModule["listWhatsAppDirectoryPeersFromConfig"] =
  ((...args) =>
    loadFacadeModule()["listWhatsAppDirectoryPeersFromConfig"](
      ...args,
    )) as FacadeModule["listWhatsAppDirectoryPeersFromConfig"];
export const resolveWhatsAppAccount: FacadeModule["resolveWhatsAppAccount"] = ((...args) =>
  loadFacadeModule()["resolveWhatsAppAccount"](...args)) as FacadeModule["resolveWhatsAppAccount"];
export const resolveWhatsAppGroupRequireMention: FacadeModule["resolveWhatsAppGroupRequireMention"] =
  ((...args) =>
    loadFacadeModule()["resolveWhatsAppGroupRequireMention"](
      ...args,
    )) as FacadeModule["resolveWhatsAppGroupRequireMention"];
export const resolveWhatsAppGroupToolPolicy: FacadeModule["resolveWhatsAppGroupToolPolicy"] = ((
  ...args
) =>
  loadFacadeModule()["resolveWhatsAppGroupToolPolicy"](
    ...args,
  )) as FacadeModule["resolveWhatsAppGroupToolPolicy"];
export const resolveWhatsAppOutboundTarget: FacadeModule["resolveWhatsAppOutboundTarget"] = ((
  ...args
) =>
  loadFacadeModule()["resolveWhatsAppOutboundTarget"](
    ...args,
  )) as FacadeModule["resolveWhatsAppOutboundTarget"];
export const whatsappAccessControlTesting: FacadeModule["whatsappAccessControlTesting"] =
  createLazyFacadeObjectValue(
    () => loadFacadeModule()["whatsappAccessControlTesting"] as object,
  ) as FacadeModule["whatsappAccessControlTesting"];
export type WebChannelStatus = FacadeEntry["types"]["WebChannelStatus"];
export type WebInboundMessage = FacadeEntry["types"]["WebInboundMessage"];
export type WebListenerCloseReason = FacadeEntry["types"]["WebListenerCloseReason"];
export type WebMonitorTuning = FacadeEntry["types"]["WebMonitorTuning"];
