// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  applyXaiModelCompat,
  buildXaiCatalogModels,
  buildXaiModelDefinition,
  buildXaiProvider,
  HTML_ENTITY_TOOL_CALL_ARGUMENTS_ENCODING,
  isModernXaiModel,
  normalizeXaiModelId,
  resolveXaiCatalogEntry,
  resolveXaiForwardCompatModel,
  XAI_BASE_URL,
  XAI_DEFAULT_CONTEXT_WINDOW,
  XAI_DEFAULT_MODEL_ID,
  XAI_DEFAULT_MODEL_REF,
  XAI_DEFAULT_MAX_TOKENS,
  XAI_TOOL_SCHEMA_PROFILE,
} from "../../extensions/xai/api.js";
