// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["xai"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "xai",
    artifactBasename: "api.js",
  });
}
export const applyXaiConfig: FacadeModule["applyXaiConfig"] = ((...args) =>
  loadFacadeModule()["applyXaiConfig"](...args)) as FacadeModule["applyXaiConfig"];
export const applyXaiProviderConfig: FacadeModule["applyXaiProviderConfig"] = ((...args) =>
  loadFacadeModule()["applyXaiProviderConfig"](...args)) as FacadeModule["applyXaiProviderConfig"];
export const applyXaiModelCompat: FacadeModule["applyXaiModelCompat"] = ((...args) =>
  loadFacadeModule()["applyXaiModelCompat"](...args)) as FacadeModule["applyXaiModelCompat"];
export const buildXaiCatalogModels: FacadeModule["buildXaiCatalogModels"] = ((...args) =>
  loadFacadeModule()["buildXaiCatalogModels"](...args)) as FacadeModule["buildXaiCatalogModels"];
export const buildXaiModelDefinition: FacadeModule["buildXaiModelDefinition"] = ((...args) =>
  loadFacadeModule()["buildXaiModelDefinition"](
    ...args,
  )) as FacadeModule["buildXaiModelDefinition"];
export const buildXaiProvider: FacadeModule["buildXaiProvider"] = ((...args) =>
  loadFacadeModule()["buildXaiProvider"](...args)) as FacadeModule["buildXaiProvider"];
export const HTML_ENTITY_TOOL_CALL_ARGUMENTS_ENCODING: FacadeModule["HTML_ENTITY_TOOL_CALL_ARGUMENTS_ENCODING"] =
  loadFacadeModule()["HTML_ENTITY_TOOL_CALL_ARGUMENTS_ENCODING"];
export const isModernXaiModel: FacadeModule["isModernXaiModel"] = ((...args) =>
  loadFacadeModule()["isModernXaiModel"](...args)) as FacadeModule["isModernXaiModel"];
export const normalizeXaiModelId: FacadeModule["normalizeXaiModelId"] = ((...args) =>
  loadFacadeModule()["normalizeXaiModelId"](...args)) as FacadeModule["normalizeXaiModelId"];
export const resolveXaiCatalogEntry: FacadeModule["resolveXaiCatalogEntry"] = ((...args) =>
  loadFacadeModule()["resolveXaiCatalogEntry"](...args)) as FacadeModule["resolveXaiCatalogEntry"];
export const resolveXaiForwardCompatModel: FacadeModule["resolveXaiForwardCompatModel"] = ((
  ...args
) =>
  loadFacadeModule()["resolveXaiForwardCompatModel"](
    ...args,
  )) as FacadeModule["resolveXaiForwardCompatModel"];
export const XAI_BASE_URL: FacadeModule["XAI_BASE_URL"] = loadFacadeModule()["XAI_BASE_URL"];
export const XAI_DEFAULT_CONTEXT_WINDOW: FacadeModule["XAI_DEFAULT_CONTEXT_WINDOW"] =
  loadFacadeModule()["XAI_DEFAULT_CONTEXT_WINDOW"];
export const XAI_DEFAULT_MODEL_ID: FacadeModule["XAI_DEFAULT_MODEL_ID"] =
  loadFacadeModule()["XAI_DEFAULT_MODEL_ID"];
export const XAI_DEFAULT_MODEL_REF: FacadeModule["XAI_DEFAULT_MODEL_REF"] =
  loadFacadeModule()["XAI_DEFAULT_MODEL_REF"];
export const XAI_DEFAULT_MAX_TOKENS: FacadeModule["XAI_DEFAULT_MAX_TOKENS"] =
  loadFacadeModule()["XAI_DEFAULT_MAX_TOKENS"];
export const XAI_TOOL_SCHEMA_PROFILE: FacadeModule["XAI_TOOL_SCHEMA_PROFILE"] =
  loadFacadeModule()["XAI_TOOL_SCHEMA_PROFILE"];
