// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  applyXiaomiConfig,
  buildXiaomiProvider,
  XIAOMI_DEFAULT_MODEL_ID,
  XIAOMI_DEFAULT_MODEL_REF,
} from "../../extensions/xiaomi/api.js";
