// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  applyZaiConfig,
  applyZaiProviderConfig,
  ZAI_CN_BASE_URL,
  ZAI_CODING_CN_BASE_URL,
  ZAI_CODING_GLOBAL_BASE_URL,
  ZAI_DEFAULT_MODEL_ID,
  ZAI_DEFAULT_MODEL_REF,
  ZAI_GLOBAL_BASE_URL,
} from "../../extensions/zai/api.js";
