// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["zai"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "zai",
    artifactBasename: "api.js",
  });
}
export const applyZaiConfig: FacadeModule["applyZaiConfig"] = ((...args) =>
  loadFacadeModule()["applyZaiConfig"](...args)) as FacadeModule["applyZaiConfig"];
export const applyZaiProviderConfig: FacadeModule["applyZaiProviderConfig"] = ((...args) =>
  loadFacadeModule()["applyZaiProviderConfig"](...args)) as FacadeModule["applyZaiProviderConfig"];
export const ZAI_CN_BASE_URL: FacadeModule["ZAI_CN_BASE_URL"] =
  loadFacadeModule()["ZAI_CN_BASE_URL"];
export const ZAI_CODING_CN_BASE_URL: FacadeModule["ZAI_CODING_CN_BASE_URL"] =
  loadFacadeModule()["ZAI_CODING_CN_BASE_URL"];
export const ZAI_CODING_GLOBAL_BASE_URL: FacadeModule["ZAI_CODING_GLOBAL_BASE_URL"] =
  loadFacadeModule()["ZAI_CODING_GLOBAL_BASE_URL"];
export const ZAI_DEFAULT_MODEL_ID: FacadeModule["ZAI_DEFAULT_MODEL_ID"] =
  loadFacadeModule()["ZAI_DEFAULT_MODEL_ID"];
export const ZAI_DEFAULT_MODEL_REF: FacadeModule["ZAI_DEFAULT_MODEL_REF"] =
  loadFacadeModule()["ZAI_DEFAULT_MODEL_REF"];
export const ZAI_GLOBAL_BASE_URL: FacadeModule["ZAI_GLOBAL_BASE_URL"] =
  loadFacadeModule()["ZAI_GLOBAL_BASE_URL"];
